SELECT CODE_SUBDIV, COUNT_NUMBER, COUNT_DOC_NOTE, VTIME,
    ROUND({0}.GET_AVERAGE_NUMBER_FOR_SUBDIV(SUBDIV_ID, 
        (select DATE_SALARY from {0}.SUBDIV_FOR_TABLE S WHERE S.SUBDIV_ID = V.SUBDIV_ID)), 0) AVERAGE_NUMBER
FROM (
    select (SELECT S.CODE_SUBDIV FROM {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV, T.SUBDIV_ID,
        COUNT(DISTINCT T.PER_NUM) COUNT_NUMBER, COUNT(DOC_NOTE) COUNT_DOC_NOTE, SUM(V.VTIME) VTIME
    from 
    (
        select W.PER_NUM, W.TRANSFER_ID, 
            ROUND(WP.VALID_TIME/3600,2) VTIME, D.DOC_NOTE
        from {0}.WORKED_DAY W
        join {0}.WORK_PAY_TYPE WP on W.WORKED_DAY_ID = WP.WORKED_DAY_ID
        join {0}.REG_DOC R on WP.REG_DOC_ID = R.REG_DOC_ID
        join {0}.DOC_LIST D on R.DOC_LIST_ID = D.DOC_LIST_ID
        where W.WORK_DATE BETWEEN :p_BEGIN_PERIOD AND :p_END_PERIOD and ROUND(FROM_GRAPH/3600,2) > 
            ROUND(FROM_PERCO/3600,2) - 
                ROUND(nvl((select sum(WP3.VALID_TIME) from {0}.WORK_PAY_TYPE WP3 
                            join {0}.REG_DOC R1 on WP3.REG_DOC_ID = R1.REG_DOC_ID
                            join {0}.DOC_LIST D1 on R1.DOC_LIST_ID = D1.DOC_LIST_ID
                            where W.WORKED_DAY_ID = WP3.WORKED_DAY_ID and D1.DOC_TYPE = 2
                            group by WP3.WORKED_DAY_ID),0)/3600,2)
            and D.DOC_LIST_ID in (11, 63, 61)) V
    join {0}.TRANSFER T on V.TRANSFER_ID = T.TRANSFER_ID
    GROUP BY T.SUBDIV_ID) V
ORDER BY CODE_SUBDIV