select TR.TRANSFER_ID,TR.PER_NUM, TR.DATE_TRANSFER,
    (select S.CODE_SUBDIV from {0}.SUBDIV S where TR.SUBDIV_ID = S.SUBDIV_ID) CODE_SUBDIV, 
    (select E.EMP_LAST_NAME from {0}.EMP E where TR.PER_NUM = E.PER_NUM) EMP_LAST_NAME, 
    (select E.EMP_FIRST_NAME from {0}.EMP E where TR.PER_NUM = E.PER_NUM) EMP_FIRST_NAME, 
    (select E.EMP_MIDDLE_NAME from {0}.EMP E where TR.PER_NUM = E.PER_NUM) EMP_MIDDLE_NAME, 
    DECODE(TR.SIGN_COMB,1,'X') COMB, TR.SIGN_COMB,
    (select P.POS_NAME from {0}.POSITION P where TR.POS_ID = P.POS_ID) POS_NAME,
    (SELECT TT.TYPE_TRANSFER_NAME FROM {0}.TYPE_TRANSFER TT 
    WHERE TR.TYPE_TRANSFER_ID = TT.TYPE_TRANSFER_ID) TYPE_TRANSFER_NAME,
    NVL((SELECT 1 FROM {0}.TRANSFER_OVERTIME TRO WHERE TRO.TRANSFER_ID = TR.TRANSFER_ID),0) SIGN_OVERTIME,
	(SELECT TRANSFER_OVERTIME_ID FROM {0}.TRANSFER_OVERTIME TRO WHERE TRO.TRANSFER_ID = TR.TRANSFER_ID) TRANSFER_OVERTIME_ID
from {0}.TRANSFER TR
WHERE TR.WORKER_ID =
    (select WORKER_ID FROM {0}.TRANSFER T1 WHERE T1.TRANSFER_ID = :p_TRANSFER_ID)
order by DATE_TRANSFER