select 1 from {0}.ORDER_ON_HOLIDAY OOH
join {0}.DATE_FOR_ORDER DFO using(ORDER_ON_HOLIDAY_ID)
join {0}.EMP_FOR_ORDER EFO using(DATE_FOR_ORDER_ID)
where OOH.SUBDIV_ID = :p_SUBDIV_ID and DFO.DATE_WORK_ORDER = TRUNC(:p_DATE_WORK) and
    EFO.SIGN_HOLIDAY = :p_SIGN_HOLIDAY and
    OOH.DATE_CLOSING_ORDER is not null and
    EFO.TRANSFER_ID in (select TRANSFER_ID from {0}.TRANSFER T0 where T0.WORKER_ID =
        (select WORKER_ID from {0}.TRANSFER T1 where T1.TRANSFER_ID = :p_TRANSFER_ID))