select (select GW.GR_WORK_NAME from {0}.GR_WORK GW where AGW.GR_WORK_ID = GW.GR_WORK_ID) GR_WORK_NAME,
    (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = AGW.SUBDIV_ID) CODE_SUBDIV,
    (select GW.DATE_END_GRAPH from {0}.GR_WORK GW where AGW.GR_WORK_ID = GW.GR_WORK_ID) DATE_END_GRAPH
from {0}.ACCESS_GR_WORK AGW
where AGW.GR_WORK_ID in (select GD.GR_WORK_ID from {0}.GR_WORK_DAY GD
where GD.TIME_ZONE_ID = :p_TIME_ZONE_ID or GD.COMPACT_TIME_ZONE_ID = :p_TIME_ZONE_ID or 
    GD.HOLIDAY_TIME_ZONE_ID = :p_TIME_ZONE_ID) 
ORDER BY GR_WORK_NAME, CODE_SUBDIV