select MAX(DATE_APPROVAL) DATE_APPROVAL from {0}.TABLE_APPROVAL
where TABLE_CLOSING_ID = :p_TABLE_CLOSING_ID and 
    TABLE_PLAN_APPROVAL_ID = (select MAX(TABLE_PLAN_APPROVAL_ID) from {0}.TABLE_PLAN_APPROVAL TPA
            where TPA.TYPE_TABLE_ID = 2)