select DECODE(GROUPING(V.PER_NUM)+GROUPING(V.CODE_SUBDIV),0,V.PER_NUM,
        1, 'Итого по подразделению',2,'Всего по подразделению') PER_NUM, V.CODE_DEGREE, 
    DECODE(GROUPING(V.CODE_DEGREE),0,E.EMP_LAST_NAME||' '||Substr(E.EMP_FIRST_NAME,1,1)||'.'||Substr(E.EMP_MIDDLE_NAME,1,1)||'.') FIO,
    SUM(TIME) TIME, (SELECT O.ORDER_NAME FROM {0}.ORDERS O where O.ORDER_ID = V.ORDER_ID) ORDER_NAME
from ( 
    select (select CODE_SUBDIV from {0}.SUBDIV S where T.SUBDIV_ID=S.SUBDIV_ID) CODE_SUBDIV, 
		TS.PER_NUM, CODE_DEGREE, SUM(TIME) TIME, ORDER_ID
    from {0}.TEMP_SALARY TS
	join {0}.TRANSFER T on T.TRANSFER_ID = TS.TRANSFER_ID
    where TEMP_SALARY_ID = :p_temp_salary_id and PAY_TYPE_ID = '102'
    GROUP BY T.SUBDIV_ID,TS.PER_NUM, CODE_DEGREE, ORDER_ID
	ORDER BY CODE_SUBDIV,TS.PER_NUM, CODE_DEGREE) V
join {0}.EMP E on V.PER_NUM = E.PER_NUM
GROUP BY ROLLUP((V.CODE_SUBDIV, V.PER_NUM,V.CODE_DEGREE, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME, V.ORDER_ID))