select TC.TYPE_CONDITION_ID, 
	CASE WHEN PARENT_ID is not null THEN '  - ' END ||TYPE_CONDITION_NAME TYPE_CONDITION_NAME, 
	PROJECT_WORK_CONDITIONS_ID, PROJECT_TRANSFER_ID, 
    PWC.TYPE_CONDITION_ID TYPE_CONDITION_ID_REF,  
    (select CW.SUBCLASS_NUMBER from {0}.CONDITIONS_OF_WORK CW 
    where CW.CONDITIONS_OF_WORK_ID=PWC.CONDITIONS_OF_WORK_ID) SUBCLASS_NUMBER,
	CONDITIONS_OF_WORK_ID, SIGN_MAIN_TYPE
from {0}.TYPE_CONDITION TC
left join 
    (select * from {0}.PROJECT_WORK_CONDITIONS PWC
    where PWC.PROJECT_TRANSFER_ID = :p_PROJECT_TRANSFER_ID) PWC on TC.TYPE_CONDITION_ID = PWC.TYPE_CONDITION_ID
ORDER BY ORDER_FOR_CONTRACT