with TERM as ( 
    select TYPE_TERM, SIGN_BASE_TEMP_TRANSFER, SIGN_REPL_EMP, BASE_TERM_TRANSFER_NAME, DATE_TERM_TRANSFER,
        (select LISTAGG((select E.EMP_LAST_NAME||' '||Substr(E.EMP_FIRST_NAME,1,1)||'.'||Substr(E.EMP_MIDDLE_NAME,1,1) 
                        from {0}.EMP E join {0}.TRANSFER T using(PER_NUM) 
                        where T.TRANSFER_ID = LRE.TRANSFER_ID), ',') 
            WITHIN GROUP(ORDER BY LRE.ORDER_REPL_EMP) 
        FROM {0}.PROJECT_LIST_REPL_EMP LRE     
        WHERE LRE.PROJECT_TERM_TRANSFER_ID = PTT.PROJECT_TERM_TRANSFER_ID) LIST_REPL_EMP
    from {0}.PROJECT_TERM_TRANSFER PTT 
    LEFT JOIN {0}.TYPE_TERM_TRANSFER TTT using(TYPE_TERM_TRANSFER_ID)
    LEFT JOIN {0}.BASE_TERM_TRANSFER BTT using(BASE_TERM_TRANSFER_ID)
    WHERE PTT.PROJECT_TRANSFER_ID = :p_PROJECT_TRANSFER_ID and TYPE_TERM = 1
    )
select E.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME,
    PT.TR_NUM_ORDER, PT.TR_DATE_ORDER, PT.DATE_HIRE, PT.DATE_TRANSFER,
    (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = PT.SUBDIV_ID) CODE_SUBDIV,
    (select S.SUBDIV_NAME from {0}.SUBDIV S where S.SUBDIV_ID = PT.SUBDIV_ID) SUBDIV_NAME,
    (select P.POS_NAME from {0}.POSITION P where P.POS_ID = PT.POS_ID) POS_NAME,
	POS_NOTE,
    (select P.CODE_POS from {0}.POSITION P where P.POS_ID = PT.POS_ID) CODE_POS,
    PT.CLASSIFIC, PT.SALARY, PT.SIGN_COMB,
    (select TG.CODE_TARIFF_GRID from {0}.TARIFF_GRID TG where TG.TARIFF_GRID_ID = PT.TARIFF_GRID_ID) CODE_TARIFF_GRID,
    Rtrim(CASE WHEN COMB_ADDITION > 0 THEN ' совмещение - '||COMB_ADDITION||';' ELSE '' END ||
        CASE WHEN HARMFUL_ADDITION_ADD > 0 THEN ' вредность доп. - '||HARMFUL_ADDITION_ADD||';' ELSE '' END, ';')
    NOTE_ADDITION_BY_HIRE,
    (select FP.NAME_FORM_PAY from {0}.FORM_PAY FP where FP.FORM_PAY = PT.FORM_PAY) NAME_FORM_PAY,
    (select D.CODE_DEGREE from {0}.DEGREE D where D.DEGREE_ID = PT.DEGREE_ID) CODE_DEGREE,
    (select D.DEGREE_NAME from {0}.DEGREE D where D.DEGREE_ID = PT.DEGREE_ID) DEGREE_NAME, 
    PT.SIGN_ADD, PT.DATE_ADD, PT.PROBA_PERIOD, PT.CONTR_EMP, PT.DATE_CONTR, 
	(SELECT DATE_TERM_TRANSFER FROM TERM) DATE_TERM_TRANSFER,
    (SELECT LIST_REPL_EMP FROM TERM) LIST_REPL_EMP,
	(select BD.BASE_DOC_NAME from {0}.BASE_DOC BD where BD.BASE_DOC_ID = PT.BASE_DOC_ID) BASE_DOC_NAME,
	(select RD.REASON_ARTICLE from {0}.REASON_DISMISS RD where RD.REASON_ID = PT.REASON_ID) REASON_ARTICLE,
	(select RD.REASON_ORDER from {0}.REASON_DISMISS RD where RD.REASON_ID = PT.REASON_ID) REASON_ORDER,
	'' REASON_ORDER1, '' REASON_ORDER2,
	BASE_DOC_NOTE
from {0}.PROJECT_TRANSFER PT
join {0}.EMP E on PT.PER_NUM = E.PER_NUM
where PT.PROJECT_TRANSFER_ID = :p_PROJECT_TRANSFER_ID