MERGE INTO {0}.CHANGE_HARMFUL CH
USING (select :p_TRANSFER_ID TRANSFER_ID, :p_date_end VALIDITY, :PERCENTAGE_OF_EMPLOYMENT PERCENTAGE_OF_EMPLOYMENT from dual) CH1
    ON (CH.TRANSFER_ID = CH1.TRANSFER_ID and CH.VALIDITY = CH1.VALIDITY)
WHEN MATCHED THEN 
    UPDATE SET CH.PERCENTAGE_OF_EMPLOYMENT = CH1.PERCENTAGE_OF_EMPLOYMENT
WHEN NOT MATCHED THEN
    INSERT(CHANGE_HARMFUL_ID, TRANSFER_ID, VALIDITY, PERCENTAGE_OF_EMPLOYMENT)
    VALUES({0}.CHANGE_HARMFUL_ID_SEQ.nextval, CH1.TRANSFER_ID, CH1.VALIDITY, CH1.PERCENTAGE_OF_EMPLOYMENT)