select ORDER_ON_HOLIDAY_ID, O.DATE_CLOSING_ORDER, O.NUM_ORDER, O.DATE_ORDER, 
    decode(O.SIGN_ORDER_PLANT,1,'X',null) as SIGN_ORDER_PLANT, decode(O.SIGN_SURNAMES_ORDER,1,'X',null) as SIGN_SURNAMES_ORDER, 
    (select PT.PAY_TYPE_NAME from {0}.PAY_TYPE PT where O.PAY_TYPE_ID = PT.PAY_TYPE_ID) PAY_TYPE_NAME, 
    O.BASE_ORDER, O.OFFICIAL, 
    SUM(DECODE(D.CODE_DEGREE,'01',EFO.COUNT_HOURS)) "01", SUM(DECODE(D.CODE_DEGREE,'02',EFO.COUNT_HOURS)) "02", 
    SUM(DECODE(D.CODE_DEGREE,'04',EFO.COUNT_HOURS)) "04", SUM(DECODE(D.CODE_DEGREE,'05',EFO.COUNT_HOURS)) "05", 
    SUM(DECODE(D.CODE_DEGREE,'08',EFO.COUNT_HOURS)) "08", SUM(DECODE(D.CODE_DEGREE,'09',EFO.COUNT_HOURS)) "09", 
    SUM(DECODE(D.CODE_DEGREE,'11',EFO.COUNT_HOURS)) "11", SUM(DECODE(D.CODE_DEGREE,'13',EFO.COUNT_HOURS)) "13",
    SUM(EFO.COUNT_HOURS) "Итого"
from {0}.ORDER_ON_HOLIDAY O
left join {0}.DATE_FOR_ORDER D using(ORDER_ON_HOLIDAY_ID)
left join {0}.EMP_FOR_ORDER EFO using(DATE_FOR_ORDER_ID)
left join {0}.TRANSFER TR using(TRANSFER_ID)
left join {0}.DEGREE D using(DEGREE_ID)
where O.SUBDIV_ID = :subdiv_id and  
    (nvl(:p_pay_type_id,0) = 0 or (nvl(:p_pay_type_id,0) != 0 and O.PAY_TYPE_ID = :p_pay_type_id))
    and (D.DATE_WORK_ORDER is null or D.DATE_WORK_ORDER between :d_b and :d_e) 
GROUP BY ORDER_ON_HOLIDAY_ID, O.DATE_CLOSING_ORDER, O.NUM_ORDER, O.DATE_ORDER, O.SIGN_ORDER_PLANT, O.SIGN_SURNAMES_ORDER, 
    O.PAY_TYPE_ID, O.BASE_ORDER, O.OFFICIAL 	
order by O.DATE_ORDER