select V.CODE_SUBDIV, V.CODE_DEGREE, V.DEG_NOTE, V.DEG_PRIORITY,
    COUNT(DISTINCT V.PER_NUM) COUNT_NUMBER, 
    COUNT(DISTINCT CASE WHEN (select E.EMP_SEX from {0}.EMP E where V.PER_NUM = E.PER_NUM) = 'Æ' THEN V.PER_NUM END) COUNT_WOMAN
from (
    select DA.DEG_NOTE, DA.DEG_PRIORITY, 
        (select D.CODE_DEGREE from {0}.DEGREE D where D.DEGREE_ID = ST.DEGREE_ID) CODE_DEGREE,
        (select T.PER_NUM from {0}.TRANSFER T where T.TRANSFER_ID = ST.TRANSFER_ID) PER_NUM,
        (select (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = T.SUBDIV_ID) 
        from {0}.TRANSFER T where T.TRANSFER_ID = ST.TRANSFER_ID) CODE_SUBDIV
    from {1}.SALARY_FROM_TABLE ST
    join {0}.DEGREE_AVG_NUMBER DA 
        on ST.DEGREE_ID = DA.DEGREE_ID and ST.CODE_F_O in (DA.CODE_F_O1, DA.CODE_F_O2) 
            and ST.CODE_POS in (DA.CODE_POS1,DA.CODE_POS2,DA.CODE_POS3)
		and DA.SIGN_REP_ECON = 1
    where ST.APP_NAME_ID = 1 and ST.END_PERIOD = :p_end_date and ST.SIGN_COMB = 0 and ST.SIGN_APPENDIX = 1
) V
GROUP BY V.CODE_SUBDIV, V.CODE_DEGREE, V.DEG_NOTE, V.DEG_PRIORITY
ORDER BY V.CODE_SUBDIV, V.DEG_PRIORITY