select CODE_SUBDIV, EXTRACT(MONTH FROM ST.START_PERIOD) NUM_MONTH, D.CODE_DEGREE, DA.DEG_NOTE, DA.DEG_PRIORITY, DA.DEG_NUM_GROUP, DA.DEG_LEVEL, SIGN_INDUST_PERS,
	SUM(CASE when PAY_TYPE_ID = 101 or (CODE_DEGREE in ('01', '02') and PAY_TYPE_ID in ('510'))  
        THEN round(TIME,0) 
        ELSE CASE when /*PAY_TYPE_ID = 102*/PAY_TYPE_ID in (102,122) or (CODE_DEGREE not in ('01', '02') and PAY_TYPE_ID in ('510'))  
                /*THEN trunc(TIME,0) */
				THEN round(TIME,0)
                ELSE null 
            END
        END) HOURS_101,
	SUM(CASE WHEN PAY_TYPE_ID = 106 THEN round(TIME,0) END) HOURS_106,
	SUM(CASE WHEN PAY_TYPE_ID = 125 THEN round(TIME,0) END) HOURS_125,
	SUM(CASE WHEN PAY_TYPE_ID = 124 THEN round(TIME,0) END) HOURS_124
from {1}.SALARY_FROM_TABLE ST
join {0}.DEGREE_AVG_NUMBER DA 
	on ST.DEGREE_ID = DA.DEGREE_ID and ST.CODE_F_O in (DA.CODE_F_O1, DA.CODE_F_O2) 
		and ST.CODE_POS in (DA.CODE_POS1,DA.CODE_POS2,DA.CODE_POS3)
		and DA.SIGN_REP_ECON = 1
join {0}.TRANSFER T using(TRANSFER_ID)
join {0}.SUBDIV S using(SUBDIV_ID)
join {0}.DEGREE D on ST.DEGREE_ID = D.DEGREE_ID
where ST.APP_NAME_ID = 1 and ST.START_PERIOD<=:p_end_date and ST.END_PERIOD>=TRUNC(:p_begin_date, 'YEAR')
	and ST.SIGN_APPENDIX = 1 and ST.SIGN_COMB = 0 
	and PAY_TYPE_ID in ('101', '102', '106', '125', '124', '510', '122')
GROUP BY CODE_SUBDIV, D.CODE_DEGREE, DA.DEG_NOTE, DA.DEG_PRIORITY, EXTRACT(MONTH FROM ST.START_PERIOD), DA.DEG_NUM_GROUP, DA.DEG_LEVEL, SIGN_INDUST_PERS
ORDER BY CODE_SUBDIV, NUM_MONTH,DEG_PRIORITY 