select TABLE_APPROVAL_ID, TABLE_CLOSING_ID, PA.TABLE_PLAN_APPROVAL_ID, PPA.NOTE_ROLE_NAME, 
    DATE_APPROVAL, NOTE_APPROVAL, TYPE_APPROVAL_TABLE_ID,
    (select TYPE_APPROVAL_TABLE_NAME from {0}.TYPE_APPROVAL_TABLE TA where TA.TYPE_APPROVAL_TABLE_ID = PA.TYPE_APPROVAL_TABLE_ID) TYPE_APPROVAL_TABLE_NAME,
    USER_NAME, (select EMP_LAST_NAME||' '||EMP_FIRST_NAME||' '||EMP_MIDDLE_NAME 
    FROM {0}.EMP E WHERE E.PER_NUM = {0}.GET_PER_NUM_FROM_USER_NAME(PA.USER_NAME)) USER_FIO
from {0}.TABLE_APPROVAL PA
LEFT JOIN {0}.TABLE_PLAN_APPROVAL PPA on (PA.TABLE_PLAN_APPROVAL_ID=PPA.TABLE_PLAN_APPROVAL_ID)
WHERE PA.TABLE_CLOSING_ID = :p_TABLE_CLOSING_ID
ORDER BY DATE_APPROVAL