select DATE_FOR_ORDER_ID, DATE_WORK_ORDER, RESPONSIBLE_WORKER,
    SUM(DECODE(D.CODE_DEGREE,'01',EFO.COUNT_HOURS)) "01", SUM(DECODE(D.CODE_DEGREE,'02',EFO.COUNT_HOURS)) "02", 
    SUM(DECODE(D.CODE_DEGREE,'04',EFO.COUNT_HOURS)) "04", SUM(DECODE(D.CODE_DEGREE,'05',EFO.COUNT_HOURS)) "05", 
    SUM(DECODE(D.CODE_DEGREE,'08',EFO.COUNT_HOURS)) "08", SUM(DECODE(D.CODE_DEGREE,'09',EFO.COUNT_HOURS)) "09", 
    SUM(DECODE(D.CODE_DEGREE,'11',EFO.COUNT_HOURS)) "11", SUM(DECODE(D.CODE_DEGREE,'13',EFO.COUNT_HOURS)) "13", 
    SUM(EFO.COUNT_HOURS) "Итого"
from {0}.DATE_FOR_ORDER DFO 
join {0}.EMP_FOR_ORDER EFO using(DATE_FOR_ORDER_ID)
join {0}.TRANSFER TR using(TRANSFER_ID)
join {0}.DEGREE D using(DEGREE_ID)
where DFO.ORDER_ON_HOLIDAY_ID = :p_ORDER_ON_HOLIDAY_ID 
GROUP BY DATE_FOR_ORDER_ID, DATE_WORK_ORDER, RESPONSIBLE_WORKER     
order by DATE_WORK_ORDER