select DECODE(GROUPING(V.CODE_SUBDIV)+GROUPING(V.PER_NUM),0, CODE_SUBDIV,
    1, 'Итого по подразделению',2,'Всего по предприятию') CODE_SUBDIV, 
    V.PER_NUM, V.CODE_DEGREE, 
    DECODE(GROUPING(V.CODE_DEGREE),0,E.EMP_LAST_NAME||' '||Substr(E.EMP_FIRST_NAME,1,1)||'.'||Substr(E.EMP_MIDDLE_NAME,1,1)||'.') FIO,
    SUM(TIME) TIME, (SELECT O.ORDER_NAME FROM {0}.ORDERS O where O.ORDER_ID = V.ORDER_ID) ORDER_NAME
from ( 
    select (select CODE_SUBDIV from {0}.SUBDIV S where T.SUBDIV_ID=S.SUBDIV_ID) CODE_SUBDIV, 
        TS.PER_NUM, CODE_DEGREE, SUM(TIME) TIME, ORDER_ID
    from {1}.SALARY_FROM_TABLE TS
    join {0}.TRANSFER T on T.TRANSFER_ID = TS.TRANSFER_ID
    join {0}.DEGREE D on TS.DEGREE_ID = D.DEGREE_ID
    where TRUNC(TS.START_PERIOD,'MONTH') <= :p_endDate and TRUNC(TS.START_PERIOD,'MONTH') >= :p_beginDate
		and PAY_TYPE_ID = '102'
    GROUP BY T.SUBDIV_ID,TS.PER_NUM, CODE_DEGREE, ORDER_ID
    ORDER BY CODE_SUBDIV,TS.PER_NUM, CODE_DEGREE) V
join {0}.EMP E on V.PER_NUM = E.PER_NUM
GROUP BY ROLLUP(V.CODE_SUBDIV, (V.PER_NUM,V.CODE_DEGREE, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME, V.ORDER_ID))