SELECT CASE WHEN EXISTS(select null 
        from {0}.ORDER_ACCESSIBILITY
        where SUBDIV_ID = :p_SUBDIV_ID and PAY_TYPE_ID = :p_PAY_TYPE_ID
            and :p_DATE_WORK between NVL(BEGIN_ACCESSIBILITY,DATE '1000-01-01') and NVL(END_ACCESSIBILITY,DATE '3000-01-01'))
    THEN 1 ELSE 0 END SIGN_ORDER_ACCESSIBILITY FROM DUAL