select RETENTION_ID, TRANSFER_ID, DATE_ADD, DATE_START_RET, DATE_END_RET 
from {1}.RETENTION RE
where RE.TRANSFER_ID in (select TRANSFER_ID from {0}.TRANSFER T WHERE T.WORKER_ID = :p_WORKER_ID)
    and RE.PAYMENT_TYPE_ID = (select PT.PAYMENT_TYPE_ID FROM {1}.PAYMENT_TYPE PT where PT.PAY_TYPE_ID = 283)
order by DATE_START_RET desc