select V.CODE_SUBDIV, V.CODE_DEGREE, V.DEG_NOTE, V.DEG_PRIORITY,
    ROUND(sum(CASE when (V.CODE_SUBDIV = '024' and CODE_DEGREE != '04' and PAY_TYPE_ID in ('540_','124All')) or 
        (V.CODE_SUBDIV = '024' and CODE_DEGREE = '04' and PAY_TYPE_ID in ('540_','222D','124All')) or 
        (V.CODE_SUBDIV != '024' and PAY_TYPE_ID in ('540_','222D', '124All')) THEN round(TIME,0) ELSE null END) / V.DAYS,2) AVERAGE_NUMBER
from (
	select DA.DEG_NOTE, DA.DEG_PRIORITY, 
		EXTRACT(DAY FROM LAST_DAY(ST.START_PERIOD)) DAYS, 
        (select D.CODE_DEGREE from {0}.DEGREE D where D.DEGREE_ID = ST.DEGREE_ID) CODE_DEGREE,
        (select T.PER_NUM from {0}.TRANSFER T where T.TRANSFER_ID = ST.TRANSFER_ID) PER_NUM,
        (select (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = T.SUBDIV_ID) 
        from {0}.TRANSFER T where T.TRANSFER_ID = ST.TRANSFER_ID) CODE_SUBDIV,
        PAY_TYPE_ID, TIME
	from {1}.SALARY_FROM_TABLE ST
	join {0}.DEGREE_AVG_NUMBER DA 
		on ST.DEGREE_ID = DA.DEGREE_ID and ST.CODE_F_O in (DA.CODE_F_O1, DA.CODE_F_O2) 
			and ST.CODE_POS in (DA.CODE_POS1,DA.CODE_POS2,DA.CODE_POS3)
			and DA.SIGN_REP_ECON = 1
	where ST.APP_NAME_ID = 1 and ST.START_PERIOD<=:p_end_date and ST.END_PERIOD>=:p_begin_date
		and ST.SIGN_APPENDIX = 1 and ST.SIGN_COMB = 0 and PAY_TYPE_ID in ('540_','222D', '124All')
) V
GROUP BY V.CODE_SUBDIV, V.CODE_DEGREE, V.DEG_NOTE, V.DEG_PRIORITY, V.DAYS
ORDER BY V.CODE_SUBDIV, V.DEG_PRIORITY