select SIGN_ACTUAL_TIME_FOR_COUPON, V.CODE_SUBDIV, V.DATE_WORK_ORDER, NGM, 
    TO_CHAR(V.DATE_WORK_ORDER, 'DD.MM.YYYY')||DECODE(SIGN_ACTUAL_TIME,1,' (по факту)') DATE_WORK,
    TO_CHAR(TIME_BEGIN,'HH24') HOURS_BEGIN, TO_CHAR(TIME_BEGIN,'MI') MINUTE_BEGIN,
    TO_CHAR(TIME_BEGIN+COUNT_HOURS/24,'HH24') HOURS_END, TO_CHAR(TIME_BEGIN+COUNT_HOURS/24,'MI') MINUTE_END,
    (select E.EMP_LAST_NAME FROM {0}.EMP E where E.PER_NUM = T.PER_NUM) EMP_LAST_NAME,
    (select E.EMP_FIRST_NAME FROM {0}.EMP E where E.PER_NUM = T.PER_NUM) EMP_FIRST_NAME,
    (select E.EMP_MIDDLE_NAME FROM {0}.EMP E where E.PER_NUM = T.PER_NUM) EMP_MIDDLE_NAME
from
(select (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = OOH.SUBDIV_ID) CODE_SUBDIV,
        DATE_WORK_ORDER, TRANSFER_ID, COUNT_HOURS, SIGN_ACTUAL_TIME, 
		/*NVL(SIGN_ACTUAL_TIME,0)*/1 SIGN_ACTUAL_TIME_FOR_COUPON,
        (select MIN(TO_DATE('01.01.1001 '||TIME_BEGIN, 'DD.MM.YYYY HH24:MI')) TIME_BEGIN
        from {0}.SUBDIV S  
        join {0}.GR_WORK GR using(GR_WORK_ID) 
        join {0}.GR_WORK_DAY using(GR_WORK_ID)
        join {0}.TIME_INTERVAL using(TIME_ZONE_ID)
        where SUBDIV_ID = OOH.SUBDIV_ID and NUMBER_DAY = 1) TIME_BEGIN,
		(select DISTINCT FIRST_VALUE(EGM.NAME_GROUP_MASTER) OVER(ORDER BY EGM.BEGIN_GROUP DESC) from {0}.EMP_GROUP_MASTER EGM 
        where EGM.TRANSFER_ID=EFO.TRANSFER_ID and DATE_WORK_ORDER between EGM.BEGIN_GROUP and NVL(EGM.END_GROUP,DATE '3000-01-01')) NGM
    from {0}.ORDER_ON_HOLIDAY OOH
    join {0}.DATE_FOR_ORDER using(ORDER_ON_HOLIDAY_ID)
    join {0}.EMP_FOR_ORDER EFO using(DATE_FOR_ORDER_ID)
    where ORDER_ON_HOLIDAY_ID = :p_order_on_holiday_id) V
join {0}.TRANSFER T on (V.TRANSFER_ID=T.TRANSFER_ID)
order by SIGN_ACTUAL_TIME_FOR_COUPON, NGM, EMP_LAST_NAME, EMP_FIRST_NAME, EMP_MIDDLE_NAME, DATE_WORK_ORDER