WITH GRANTED_ROLES as
    (SELECT GRANTED_ROLE FROM USER_ROLE_PRIVS )
select TYPE_APPROVAL_TABLE_ID, TYPE_APPROVAL_TABLE_NAME
from {0}.TYPE_APPROVAL_TABLE TA
WHERE TA.TYPE_APPROVAL_TABLE_ID in ( 
    select TAR.TYPE_APPROVAL_TABLE_ID from {0}.TYPE_APPROVAL_TABLE_BY_ROLE TAR
    JOIN {0}.TABLE_PLAN_APPROVAL PPA on TAR.TABLE_PLAN_APPROVAL_ID = PPA.TABLE_PLAN_APPROVAL_ID 
    WHERE TAR.ROLE_NAME in (SELECT GRANTED_ROLE FROM GRANTED_ROLES ) and
        PPA.TABLE_PLAN_APPROVAL_ID = :p_TABLE_PLAN_APPROVAL_ID         
    )