with APPR as (
    select DATE_APPROVAL, USER_NAME,
        (SELECT EMP_LAST_NAME||' '||SUBSTR(EMP_FIRST_NAME,1,1)||'.'||SUBSTR(EMP_MIDDLE_NAME,1,1)||'.'
        FROM {0}.EMP E WHERE E.PER_NUM = {0}.GET_PER_NUM_FROM_USER_NAME(USER_NAME)) USER_FIO,
        ROLE_NAME, TABLE_PLAN_APPROVAL_ID,        
        DECODE(ROLE_NAME, 
            'TABLE_EDIT','Табельщик подразделения',
            'STAFF_CHIEF_SUBDIV','Руководитель подразделения',
            'STAFF_CHIEF_BUREAU_TARIFF','Начальник БТиЗ',
            'TABLE_ECON_DEV','Отдел ОТиЗП',
            'TABLE_FORM_FILE','Начальник гр. приема и табельного учёта') NOTE_ROLE_NAME,
        DECODE(ROLE_NAME, 
			'TABLE_ECON_DEV',29,
            'TABLE_EDIT',30,
            'STAFF_CHIEF_SUBDIV',29,
            'STAFF_CHIEF_BUREAU_TARIFF',30,
            'TABLE_FORM_FILE',30) ROW_INDEX,
        DECODE(ROLE_NAME, 
			'TABLE_ECON_DEV',21,
            'TABLE_EDIT',21,
            'STAFF_CHIEF_SUBDIV',8,
            'STAFF_CHIEF_BUREAU_TARIFF',8,
            'TABLE_FORM_FILE',33) COLUMN_INDEX
    from (
        select DISTINCT FIRST_VALUE(TA.DATE_APPROVAL) 
                                      OVER(PARTITION BY TPA.ROLE_NAME ORDER BY TA.DATE_APPROVAL DESC) DATE_APPROVAL, 
                    FIRST_VALUE(TA.USER_NAME) OVER(PARTITION BY TPA.ROLE_NAME ORDER BY TA.DATE_APPROVAL DESC) USER_NAME, 
                    FIRST_VALUE(TPA.ROLE_NAME) OVER(PARTITION BY TPA.ROLE_NAME ORDER BY TA.DATE_APPROVAL DESC) ROLE_NAME,
                    TA.TABLE_PLAN_APPROVAL_ID
        from {0}.TABLE_APPROVAL TA
        join {0}.TABLE_PLAN_APPROVAL TPA on TA.TABLE_PLAN_APPROVAL_ID = TPA.TABLE_PLAN_APPROVAL_ID
        where TABLE_CLOSING_ID = :p_TABLE_CLOSING_ID)
    )
select NOTE_ROLE_NAME, 'ЭЦП' NOTE, DATE_APPROVAL, USER_FIO, ROLE_NAME, ROW_INDEX, COLUMN_INDEX
from APPR 
--WHERE ROLE_NAME IN ('TABLE_EDIT','STAFF_CHIEF_SUBDIV','STAFF_CHIEF_BUREAU_TARIFF','TABLE_FORM_FILE')
WHERE ROLE_NAME IN ('STAFF_CHIEF_BUREAU_TARIFF','TABLE_ECON_DEV')
ORDER BY TABLE_PLAN_APPROVAL_ID