select PP.PRIVILEGED_POSITION_ID, 
    (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = PP.SUBDIV_ID) as CODE_SUBDIV,
    (select P.CODE_POS from {0}.POSITION P where P.POS_ID = PP.POS_ID ) as CODE_POS,
    (select P.POS_NAME from {0}.POSITION P where P.POS_ID = PP.POS_ID ) as POS_NAME,
    PP.SPECIAL_CONDITIONS, PP.KPS, PP.NUMBER_LIST
from {0}.PRIVILEGED_POSITION PP
order by CODE_SUBDIV, CODE_POS