select DISTINCT
    (SELECT S.CODE_SUBDIV FROM {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    (SELECT E.EMP_LAST_NAME||' '||Substr(E.EMP_FIRST_NAME,1,1)||'.'||Substr(E.EMP_MIDDLE_NAME,1,1)||'.'
    FROM {0}.EMP E WHERE E.PER_NUM = T.PER_NUM) FIO, 
    (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME,
    (SELECT E.EMP_BIRTH_DATE FROM {0}.EMP E WHERE E.PER_NUM = T.PER_NUM) EMP_BIRTH_DATE,
    REASON_DETENTION_NAME, 
    COUNT(*) OVER(PARTITION BY T.PER_NUM) COUNT_VIOLATIONS,
    LISTAGG(TYPE_PUNISHMENT_NAME,';'||chr(13)) WITHIN GROUP(ORDER BY DETENTION_DATE) OVER(PARTITION BY T.PER_NUM)
    TYPE_PUNISHMENT_NAME
from (
    select VE.TRANSFER_ID, DETENTION_DATE,
        (SELECT RD.REASON_DETENTION_NAME FROM {0}.REASON_DETENTION RD 
        WHERE RD.REASON_DETENTION_ID = VE.REASON_DETENTION_ID) REASON_DETENTION_NAME, 
        (SELECT TP.TYPE_PUNISHMENT_NAME FROM {0}.TYPE_PUNISHMENT TP 
        WHERE TP.TYPE_PUNISHMENT_ID = VP.TYPE_PUNISHMENT_ID)||
        CASE WHEN VP.PERCENT_PUNISHMENT is null THEN '' ELSE ' - '||VP.PERCENT_PUNISHMENT||'%' END TYPE_PUNISHMENT_NAME
    from {0}.VIOLATION_EMP VE
    left join {0}.VIOLATION_EMP_PUN VP on VP.VIOLATION_EMP_ID = VE.VIOLATION_EMP_ID
    WHERE VE.DETENTION_DATE between :p_DATE_BEGIN and :p_DATE_END
    union all
    select VT.TRANSFER_ID, DETENTION_DATE,
        (SELECT RD.REASON_DETENTION_NAME FROM {0}.REASON_DETENTION RD 
        WHERE RD.REASON_DETENTION_ID = V.REASON_DETENTION_ID) REASON_DETENTION_NAME, 
        (SELECT TP.TYPE_PUNISHMENT_NAME FROM {0}.TYPE_PUNISHMENT TP 
        WHERE TP.TYPE_PUNISHMENT_ID = LP.TYPE_PUNISHMENT_ID)||
        CASE WHEN LP.PERCENT_PUNISHMENT is null THEN '' ELSE ' - '||LP.PERCENT_PUNISHMENT||'%' END TYPE_PUNISHMENT_NAME
    from {0}.VIOLATION V
    join {0}.VIOLATOR VT on V.VIOLATION_ID = VT.VIOLATION_ID
    left join {0}.PUNISHMENT P on V.VIOLATION_ID = P.VIOLATION_ID
    left join {0}.LIST_OF_PUNISHMENT LP on P.PUNISHMENT_ID = LP.PUNISHMENT_ID
    where VT.TRANSFER_ID is not null and V.DETENTION_DATE between :p_DATE_BEGIN and :p_DATE_END
		and nvl((select SIGN_RESTRICTED_ACCESS_INFORM from {0}.STOLEN_PROPERTY SP where SP.VIOLATION_ID = V.VIOLATION_ID),0) = 0
) V
join {0}.TRANSFER T on V.TRANSFER_ID = T.TRANSFER_ID
ORDER BY CODE_SUBDIV, FIO