SELECT 
    (SELECT S.CODE_SUBDIV FROM {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV, 
    E.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME, E.EMP_BIRTH_DATE, 
    T.TRANSFER_ID, T.DATE_HIRE, T.WORKER_ID, T.CONTR_EMP, T.DATE_CONTR, T.DATE_END_CONTR
FROM {0}.Emp E
JOIN {0}.Transfer T ON E.PER_NUM = T.PER_NUM
WHERE T.TYPE_TRANSFER_ID = 8
ORDER BY PER_NUM