select CHILD_CARE_LEAVE_ID, RELATIVE_ID, DATE_BEGIN_LEAVE, DATE_END_LEAVE, BREAKPOINT_LEAVE, 
    PROLONGATION_LEAVE, DATE_DEPARTURE, SIGN_LEAVE_1_5_YEARS 
from {0}.CHILD_CARE_LEAVE CCL
where CCL.RELATIVE_ID = :p_RELATIVE_ID and 
	SIGN_LEAVE_1_5_YEARS = NVL(:p_SIGN_LEAVE_1_5_YEARS,SIGN_LEAVE_1_5_YEARS)