SELECT (SELECT S.CODE_SUBDIV FROM {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
	TRANSFER_ID, PER_NUM, SUBDIV_ID, POS_ID, TYPE_TRANSFER_ID, GR_WORK_ID, 
    DATE_HIRE, DATE_TRANSFER, DATE_END_CONTR, WORKER_ID, DEGREE_ID
FROM {0}.TRANSFER T
WHERE PER_NUM = :p_PER_NUM
ORDER BY DATE_TRANSFER