select ROWNUM RN, V.* 
from (
	select 
        LAST_NAME||' '||FIRST_NAME||' '||MIDDLE_NAME FIO,
        CODE_SUBDIV||', '||POS_NAME POS_NAME,
        TO_CHAR(DETENTION_DATE,'DD.MM.YYYY')||', '||
        (select SD.SIGN_DETENTION_NAME from {0}.SIGN_DETENTION SD 
        where SD.SIGN_DETENTION_ID = V1.SIGN_DETENTION_ID)||', '||
        (select RD.REASON_DETENTION_NAME from {0}.REASON_DETENTION RD 
        WHERE RD.REASON_DETENTION_ID = V1.REASON_DETENTION_ID) DATE_SIGN_REASON,
        V1.MEASURES_TAKEN, V1.NOTE
    from (
        select 
            (select S.CODE_SUBDIV from {0}.SUBDIV S where T.SUBDIV_ID = S.SUBDIV_ID) CODE_SUBDIV, 
            (select S.SUBDIV_NAME from {0}.SUBDIV S where T.SUBDIV_ID = S.SUBDIV_ID) SUBDIV_NAME, 
            PER_NUM, E.EMP_LAST_NAME LAST_NAME, E.EMP_FIRST_NAME FIRST_NAME, E.EMP_MIDDLE_NAME MIDDLE_NAME, 
            (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME, 
            VR.VIOLATION_ID, VR.VIOLATOR_ID, TRANSFER_ID, null as PERCO_SYNC_ID, null as OTHER_VIOLATOR_ID,
            VI.SIGN_DETENTION_ID, VI.REASON_DETENTION_ID, VI.MEASURES_TAKEN, VI.NOTE, VI.DETENTION_DATE
        from {0}.VIOLATION VI
        join {0}.VIOLATOR VR on VI.VIOLATION_ID = VR.VIOLATION_ID
        join {0}.TRANSFER T using(TRANSFER_ID)
        join {0}.EMP E using(PER_NUM)
        where VI.VIOLATION_ID in (select COLUMN_VALUE from TABLE(:p_TABLE))
        union all
        select
            (select S.SUBDIV_NAME from {0}.SUBDIV S where FR.SUBDIV_ID = S.SUBDIV_ID), 
            (select S.SUBDIV_NAME from {0}.SUBDIV S where FR.SUBDIV_ID = S.SUBDIV_ID), 
            null, UPPER(FR.FR_LAST_NAME) FR_LAST_NAME, UPPER(FR.FR_FIRST_NAME) FR_FIRST_NAME, UPPER(FR.FR_MIDDLE_NAME) FR_MIDDLE_NAME, 
            (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = FR.POS_ID) POS_NAME, 
            VR.VIOLATION_ID, VR.VIOLATOR_ID, null as TRANSFER_ID, PERCO_SYNC_ID, null as OTHER_VIOLATOR_ID,
            VI.SIGN_DETENTION_ID, VI.REASON_DETENTION_ID, VI.MEASURES_TAKEN, VI.NOTE, VI.DETENTION_DATE
        from {0}.VIOLATION VI
        join {0}.VIOLATOR VR on VI.VIOLATION_ID = VR.VIOLATION_ID
        join {0}.FR_EMP FR using(PERCO_SYNC_ID)
        where VI.VIOLATION_ID in (select COLUMN_VALUE from TABLE(:p_TABLE))
        union all
        select OV_SUBDIV_NAME, OV_SUBDIV_NAME, null, OT_LAST_NAME, OT_FIRST_NAME, OT_MIDDLE_NAME, 
            OV_POS_NAME, VR.VIOLATION_ID, VR.VIOLATOR_ID, null, null, OTHER_VIOLATOR_ID,
            VI.SIGN_DETENTION_ID, VI.REASON_DETENTION_ID, VI.MEASURES_TAKEN, VI.NOTE, VI.DETENTION_DATE
        from {0}.VIOLATION VI
        join {0}.VIOLATOR VR on VI.VIOLATION_ID = VR.VIOLATION_ID
        join {0}.OTHER_VIOLATOR using(OTHER_VIOLATOR_ID)
        where VI.VIOLATION_ID in (select COLUMN_VALUE from TABLE(:p_TABLE))
    ) V1
    ORDER BY V1.DETENTION_DATE)
V