select LIST_OF_PUNISHMENT_ID, PUNISHMENT_ID, TYPE_PUNISHMENT_ID, PERCENT_PUNISHMENT, SIGN_PUNISHMENT_CHIEF
from {0}.LIST_OF_PUNISHMENT LP
where LP.PUNISHMENT_ID = :p_PUNISHMENT_ID and SIGN_PUNISHMENT_CHIEF = :p_SIGN_PUNISHMENT_CHIEF