select DISPLAY_NAME, ID_SHABLON_MAIN, DESCRIPTION, TEMPORARY_ACC,
	DECODE(TEMPORARY_ACC,0,'Шаблон для сотрудников',
        1, 'Шаблон для посетителей',
        'Неизвестный тип шаблона...') TEMPORARY_ACC_NAME, 
	BEGIN_ACCESS, END_ACCESS,
    (SELECT LISTAGG(CODE_SUBDIV,',') WITHIN GROUP(ORDER BY CODE_SUBDIV)
    FROM {0}.ACCESS_TEMPL_BY_SUBDIV ATS JOIN {0}.SUBDIV USING(SUBDIV_ID)
    WHERE ATS.ID_SHABLON_MAIN = AT.ID_SHABLON_MAIN) ALL_CODE_SUBDIV
from {0}.ACCESS_TEMPLATE AT
ORDER BY AT.DISPLAY_NAME