select DEPENDENTS_ID, DEP_MONTH, CODE_SUBDIV, SIGN_COMB, DEP_TAX_CODE, DEP_COUNT114, DEP_COUNT115, 
    DEP_COUNT116, DEP_COUNT117, DEP_COUNT118, DEP_COUNT119, DEP_COUNT120, DEP_COUNT121
from {0}.DEPENDENTS D 
where D.PER_NUM = :p_per_num and nvl(SIGN_COMB,' ') = :p_sign_comb  
order by DEP_MONTH