WITH TP_PER AS (
        SELECT TRANSFER_ID,subdiv_id,DEGREE_ID,FORM_OPERATION_ID,trunc(date_transfer) DATE_TRANSFER,
                DECODE(sign_cur_work,1,DATE '3000-01-01', 
                    DECODE(TYPE_TRANSFER_ID,3,TRUNC(DATE_TRANSFER)+85999/86000,
                        TRUNC((SELECT MIN (date_transfer) FROM {0}.transfer
                               WHERE from_position = t.transfer_id)) - 1 / 86000)) end_transfer,
               DATE_END_CONTR,TYPE_TRANSFER_ID,POS_ID,PER_NUM,SIGN_COMB,FROM_POSITION, DATE_HIRE,
               WORKER_ID, SIGN_CUR_WORK
        FROM (
            SELECT * FROM {0}.transfer 
            WHERE HIRE_SIGN = 1 and PER_NUM in (
                SELECT PER_NUM FROM {0}.EMP E
                WHERE E.PER_NUM = NVL(:p_PER_NUM, E.PER_NUM) and 
                    E.EMP_LAST_NAME = NVL(:p_EMP_LAST_NAME, E.EMP_LAST_NAME) AND
                    E.EMP_FIRST_NAME = NVL(:p_EMP_FIRST_NAME, E.EMP_FIRST_NAME) and
                    E.EMP_MIDDLE_NAME = NVL(:p_EMP_MIDDLE_NAME, E.EMP_MIDDLE_NAME))) t           
        START WITH sign_cur_work = 1 OR type_transfer_id = 3
        CONNECT BY NOCYCLE PRIOR from_position = transfer_id)
select (SELECT S.CODE_SUBDIV FROM {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    PER_NUM, DECODE(SIGN_CUR_WORK,1,'V') CUR_WORK,
	(SELECT E.EMP_LAST_NAME||' '||E.EMP_FIRST_NAME||' '||E.EMP_MIDDLE_NAME
	FROM {0}.EMP E WHERE E.PER_NUM =T.PER_NUM) FIO,
    (SELECT P.CODE_POS FROM {0}.POSITION P WHERE P.POS_ID = T.POS_ID) CODE_POS,
    TRUNC(DATE_TRANSFER) DATE_TRANSFER, 
    CASE WHEN END_TRANSFER < DATE '3000-01-01' THEN TRUNC(END_TRANSFER) END END_TRANSFER, 
    DECODE(T.SIGN_COMB,1,'X') COMB,
    (SELECT TT.TYPE_TRANSFER_NAME FROM {0}.TYPE_TRANSFER TT 
    WHERE TT.TYPE_TRANSFER_ID = T.TYPE_TRANSFER_ID) TYPE_TRANSFER_NAME, 
    (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME
from TP_PER T
ORDER BY PER_NUM, DATE_TRANSFER