select DE.DISMISSED_EMP_ID, TRANSFER_ID, DE.DATE_PROCESSING,
    NVL2(DE.DATE_PROCESSING,1,0) SIGN_PROCESSING, SIGN_PURPOSE_RECORD,
    (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV, 
    PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME, TRUNC(T.DATE_TRANSFER) DATE_TRANSFER,
    (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME,
	SIGN_COMB, DECODE(SIGN_COMB,1,'X') COMB,
	(select S.CODE_SUBDIV from {0}.SUBDIV S join {0}.TRANSFER T1 on (S.SUBDIV_ID = T1.SUBDIV_ID) 
	where T1.TRANSFER_ID = T.FROM_POSITION) PREV_CODE_SUBDIV,
	(SELECT P.POS_NAME FROM {0}.POSITION P join {0}.TRANSFER T1 on (P.POS_ID = T1.POS_ID) 
	WHERE T1.TRANSFER_ID = T.FROM_POSITION) PREV_POS_NAME
from {0}.DISMISSED_EMP DE
join {0}.TRANSFER T using(TRANSFER_ID)
join {0}.EMP E using(PER_NUM)
WHERE SIGN_PURPOSE_RECORD = :p_SIGN_PURPOSE_RECORD and T.TYPE_TRANSFER_ID = :p_TYPE_TRANSFER_ID
order by DATE_PROCESSING, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME, DATE_TRANSFER--PER_NUM