select ACCESS_TEMPL_BY_EMP_ID, PER_NUM, ID_SHABLON_MAIN, START_DATE_VALID, END_DATE_VALID, 
	SIGN_TEMPORARY_SHABLON, PERCO_SYNC_ID, ID_CARD, 
    (SELECT DISPLAY_NAME FROM {0}.ACCESS_TEMPLATE ACT WHERE ACT.ID_SHABLON_MAIN = AC.ID_SHABLON_MAIN) DISPLAY_NAME 
from {0}.ACCESS_TEMPL_BY_EMP AC
where AC.ID_CARD = :p_ID_CARD
order by START_DATE_VALID DESC