SELECT ACCESS_TEMPL_BY_SUBDIV_ID, ID_SHABLON_MAIN, SUBDIV_ID,
    CODE_SUBDIV, SUBDIV_NAME 
FROM {0}.ACCESS_TEMPL_BY_SUBDIV
JOIN {0}.SUBDIV USING (SUBDIV_ID)
WHERE ID_SHABLON_MAIN = :p_ID_SHABLON_MAIN