select OTHER_VIOLATOR_ID, OT_LAST_NAME LAST_NAME, OT_FIRST_NAME FIRST_NAME, OT_MIDDLE_NAME MIDDLE_NAME, 
    OV_POS_NAME POS_NAME, OV_SUBDIV_NAME SUBDIV_NAME
from {0}.OTHER_VIOLATOR OV
order by OV.OT_LAST_NAME, OV.OT_FIRST_NAME, OV.OT_MIDDLE_NAME