select CODE_SUBDIV, SUBDIV_NAME, SUBDIV_ID, PER_NUM, LAST_NAME, FIRST_NAME, MIDDLE_NAME, POS_NAME,
    VIOL.VIOLATION_ID, VIOLATOR_ID, DETENTION_DATE, INFORM_SUBDIV_DATE, SIGN_DISCIPLINARY_COMM, 
    REASON_DETENTION_ID, SIGN_DETENTION_ID, MEASURES_TAKEN, NOTE, 
    SIGN_GROUP_VIOLATION,
    NVL((SELECT RD.SIGN_THEFT FROM {0}.REASON_DETENTION RD 
    WHERE RD.REASON_DETENTION_ID = VI.REASON_DETENTION_ID),0) SIGN_THEFT,
    NVL((SELECT SIGN_CRIMINAL_PROSECUTION FROM {0}.STOLEN_PROPERTY SP 
    WHERE SP.VIOLATION_ID = VIOL.VIOLATION_ID),0) SIGN_CRIMINAL_PROSECUTION,
    TRANSFER_ID, PERCO_SYNC_ID, OTHER_VIOLATOR_ID,
	(select REASON_DETENTION_NAME from {0}.REASON_DETENTION RD where RD.REASON_DETENTION_ID = VI.REASON_DETENTION_ID) REASON_DETENTION_NAME,
	(select SIGN_DETENTION_NAME from {0}.SIGN_DETENTION SD where SD.SIGN_DETENTION_ID = VI.SIGN_DETENTION_ID) SIGN_DETENTION_NAME
from (
    select 
        (select S.CODE_SUBDIV from {0}.SUBDIV S where T.SUBDIV_ID = S.SUBDIV_ID) CODE_SUBDIV, 
        (select S.SUBDIV_NAME from {0}.SUBDIV S where T.SUBDIV_ID = S.SUBDIV_ID) SUBDIV_NAME, 
        PER_NUM, E.EMP_LAST_NAME LAST_NAME, E.EMP_FIRST_NAME FIRST_NAME, E.EMP_MIDDLE_NAME MIDDLE_NAME, 
        (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME, 
        V.VIOLATION_ID, V.VIOLATOR_ID, TRANSFER_ID, null as PERCO_SYNC_ID, null as OTHER_VIOLATOR_ID,
		T.SUBDIV_ID
    from {0}.VIOLATOR V
    join {0}.TRANSFER T using(TRANSFER_ID)
    join {0}.EMP E using(PER_NUM)
    where TRANSFER_ID is not null
    union all
    select
        (select S.SUBDIV_NAME from {0}.SUBDIV S where FR.SUBDIV_ID = S.SUBDIV_ID), 
        (select S.SUBDIV_NAME from {0}.SUBDIV S where FR.SUBDIV_ID = S.SUBDIV_ID), 
        null, UPPER(FR.FR_LAST_NAME) FR_LAST_NAME, UPPER(FR.FR_FIRST_NAME) FR_FIRST_NAME, UPPER(FR.FR_MIDDLE_NAME) FR_MIDDLE_NAME, 
        (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = FR.POS_ID) POS_NAME, 
        V.VIOLATION_ID, V.VIOLATOR_ID, null as TRANSFER_ID, PERCO_SYNC_ID, null as OTHER_VIOLATOR_ID,
		FR.SUBDIV_ID
    from {0}.VIOLATOR V
    join {0}.FR_EMP FR using(PERCO_SYNC_ID)
    where PERCO_SYNC_ID is not null
    union all
    select OV_SUBDIV_NAME, OV_SUBDIV_NAME, null, OT_LAST_NAME, OT_FIRST_NAME, OT_MIDDLE_NAME, 
        OV_POS_NAME, V.VIOLATION_ID, V.VIOLATOR_ID, null, null, OTHER_VIOLATOR_ID, 
		null SUBDIV_ID
    from {0}.VIOLATOR V
    join {0}.OTHER_VIOLATOR using(OTHER_VIOLATOR_ID)
    where OTHER_VIOLATOR_ID is not null
) VIOL
join {0}.VIOLATION VI on (VIOL.VIOLATION_ID = VI.VIOLATION_ID)
where VI.VIOLATION_ID = NVL(:p_VIOLATION_ID,VI.VIOLATION_ID)
	/*and (not exists(select null from USER_ROLE_PRIVS where GRANTED_ROLE = 'STAFF_GROUP_HIRE'
                    union select null from ROLE_ROLE_PRIVS where GRANTED_ROLE = 'STAFF_GROUP_HIRE')
        or (exists(select null from USER_ROLE_PRIVS where GRANTED_ROLE = 'STAFF_GROUP_HIRE'
                    union select null from ROLE_ROLE_PRIVS where GRANTED_ROLE = 'STAFF_GROUP_HIRE')
            and ((nvl((select SIGN_RESTRICTED_ACCESS_INFORM from {0}.STOLEN_PROPERTY SP 
					where SP.VIOLATION_ID = VI.VIOLATION_ID),0) = 0) 
				or ora_login_user = 'BMW12714')
            ))*/
	and (:p_GRANTED_GROUP_HIRE = 0 
		or (:p_GRANTED_GROUP_HIRE = 1 
			and ((nvl((select SIGN_RESTRICTED_ACCESS_INFORM from {0}.STOLEN_PROPERTY SP where SP.VIOLATION_ID = VI.VIOLATION_ID),0) = 0) 
				or ora_login_user = 'BMW12714')
			))
	and (:p_TYPE_GROUP_PUNISHMENT_ID is null or 
		(:p_TYPE_GROUP_PUNISHMENT_ID is not null and exists
			(select null from {0}.LIST_OF_PUNISHMENT LOP 
			join {0}.TYPE_PUNISHMENT TP using(TYPE_PUNISHMENT_ID) 
			join {0}.PUNISHMENT PU using(PUNISHMENT_ID)
			where PU.VIOLATION_ID = VI.VIOLATION_ID and TP.TYPE_GROUP_PUNISHMENT_ID = :p_TYPE_GROUP_PUNISHMENT_ID)))
order by CODE_SUBDIV, DETENTION_DATE