select STOLEN_PROPERTY_ID, VIOLATION_ID, TYPE_STOLEN_PROPERTY_ID, UNIT_OF_MEASUREMENT, COUNT_STOLEN, SUM_STOLEN, 
    SIGN_CRIMINAL_PROSECUTION, CRIMINAL_CASE_NUMBER, DATE_OF_INITIATION, DATE_OF_DECISION, SIGN_RESTRICTED_ACCESS_INFORM
from {0}.STOLEN_PROPERTY SP
where SP.VIOLATION_ID = :p_VIOLATION_ID