WITH CARDS as (
    select * from TABLE({1}.GET_CARDS)),
    TEMPL as (
    select ATE.ACCESS_TEMPL_BY_EMP_ID, PER_NUM, ID_SHABLON_MAIN, 
        START_DATE_VALID, NVL(END_DATE_VALID, DATE '3000-01-01') END_DATE_VALID, 
        SIGN_TEMPORARY_SHABLON, PERCO_SYNC_ID, ID_CARD
    from {0}.ACCESS_TEMPL_BY_EMP ATE 
    where SYSDATE BETWEEN START_DATE_VALID and NVL(END_DATE_VALID, DATE '3000-01-01') )
SELECT 0 FL, CODE_SUBDIV, SUBDIV_ID,
        V.PER_NUM, EMP_LAST_NAME, EMP_FIRST_NAME, EMP_MIDDLE_NAME, EMP_SEX, EMP_BIRTH_DATE, COMB, SiGN_COMB, 
        POS_ID, CODE_POS, POS_NAME,
        POS_NOTE, TRANSFER_ID, FROM_POSITION,DATE_HIRE,DATE_TRANSFER, DATE_DISMISS,
        TYPE_TRANSFER_ID, WORKER_ID, V.PERCO_SYNC_ID,
        C.IDENTIFIER, C.ID_CARD, ID_SHABLON_MAIN,
        (SELECT AC.DISPLAY_NAME FROM {0}.ACCESS_TEMPLATE AC WHERE AC.ID_SHABLON_MAIN = TE.ID_SHABLON_MAIN) DISPLAY_NAME
FROM (
    SELECT 
        E.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME,
        E.EMP_MIDDLE_NAME,E.EMP_SEX, E.EMP_BIRTH_DATE, CASE T.SIGN_COMB WHEN 1 THEN 'X' ELSE '' END AS COMB, T.SiGN_COMB,
        POS_NOTE, P.CODE_POS, P.POS_NAME, CODE_SUBDIV, T.SUBDIV_ID, T.POS_ID,
        T.TRANSFER_ID, T.WORKER_ID, T.FROM_POSITION,T.DATE_HIRE , DATE_DISMISS,
        DATE_TRANSFER, T.TYPE_TRANSFER_ID, E.PERCO_SYNC_ID
    FROM {0}.Emp E 
    JOIN (SELECT TRANSFER_ID, PER_NUM, SUBDIV_ID, POS_ID, TYPE_TRANSFER_ID, DATE_HIRE, FROM_POSITION, SIGN_COMB,
                DEGREE_ID, WORKER_ID, DATE_TRANSFER, POS_NOTE, 
                CASE WHEN TYPE_TRANSFER_ID = 3 THEN TRUNC(DATE_TRANSFER) END DATE_DISMISS
            FROM {0}.Transfer 
            WHERE HIRE_SIGN = 1 and WORKER_ID = NVL(:p_WORKER_ID, WORKER_ID) and SUBDIV_ID = NVL(:p_SUBDIV_ID, SUBDIV_ID)
                and (SIGN_CUR_WORK = 1 or (TYPE_TRANSFER_ID = 3 and DATE_TRANSFER >= ADD_MONTHS(SYSDATE, -1)))) T 
        ON E.PER_NUM = T.PER_NUM
    JOIN {0}.POSITION P  on T.POS_ID = P.POS_ID
    JOIN {0}.SUBDIV S on T.SUBDIV_ID = S.SUBDIV_ID
) V
join (select * from CARDS) C on V.PER_NUM = C.PER_NUM
left join (select * from TEMPL) TE on V.PER_NUM = TE.PER_NUM and C.ID_CARD = TE.ID_CARD
WHERE C.ID_CARD = NVL(:p_ID_CARD,C.ID_CARD)
order by CODE_SUBDIV, PER_NUM, SiGN_COMB, IDENTIFIER