select FR.PERCO_SYNC_ID EMP_ID,
    (select S.SUBDIV_NAME from {0}.SUBDIV S where FR.SUBDIV_ID = S.SUBDIV_ID) CODE_SUBDIV, 
    (select S.SUBDIV_NAME from {0}.SUBDIV S where FR.SUBDIV_ID = S.SUBDIV_ID) SUBDIV_NAME, 
    FR.FR_LAST_NAME LAST_NAME, 
    FR.FR_FIRST_NAME FIRST_NAME, 
    FR.FR_MIDDLE_NAME MIDDLE_NAME, null PER_NUM, 
    null COMB, 
    (select P.POS_NAME from {0}.POSITION P where FR.POS_ID = P.POS_ID) POS_NAME
from {0}.FR_EMP FR 
where FR.FR_DATE_START <= :p_date_end and NVL(FR.FR_DATE_END,DATE '3000-01-01') >= :p_date_begin
ORDER BY SUBDIV_NAME, LAST_NAME, FIRST_NAME, MIDDLE_NAME