select P.PERMIT_ID, P.NUM_DOC_PERMIT, P.DATE_DOC_PERMIT, 
    TP.PERMIT_NAME, P.DATE_START_PERMIT, P.DATE_END_PERMIT,
	CASE WHEN not (DATE_START_PERMIT <= TRUNC(SYSDATE)
			and DATE_END_PERMIT >= TRUNC(SYSDATE)) THEN 1 ELSE 0 END FL_ARCHIV
from {0}.PERMIT P
join {0}.TYPE_PERMIT TP on P.TYPE_PERMIT_ID = TP.TYPE_PERMIT_ID
where P.TRANSFER_ID in 
    (SELECT T.transfer_id from {0}.TRANSFER T where T.WORKER_ID = :p_WORKER_ID)
order by DATE_DOC_PERMIT desc