select ROWNUM RN, V.* 
from (           
    select (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID=T.SUBDIV_ID) CODE_SUBDIV, 
        NPP.PER_NUM, E.EMP_LAST_NAME||' '||E.EMP_FIRST_NAME||' '||E.EMP_MIDDLE_NAME FIO,
        E.EMP_BIRTH_DATE, (select P.POS_NAME from {0}.POSITION P where P.POS_ID=T.POS_ID) POS_NAME,
		/*(SELECT PP.PENSION_PLAN_NAME FROM {0}.PENSION_PLAN PP 
		WHERE PP.PENSION_PLAN_ID = NPP.PENSION_PLAN_ID) PENSION_PLAN_NAME,*/
        Trunc(NPP.DATE_OF_ENTRY) DATE_OF_ENTRY,
        Trunc(NPP.DATE_SETTING_PENS) DATE_SETTING_PENS, DECODE(T.TYPE_TRANSFER_ID,3,TRUNC(T.DATE_TRANSFER)) DATE_DISMISS
    from {0}.NONSTATE_PENS_PROV NPP
    join {0}.EMP E on (NPP.PER_NUM=E.PER_NUM)
    join {0}.TRANSFER T on (T.PER_NUM=E.PER_NUM)
    where NPP.DATE_SETTING_PENS is not null and T.SIGN_COMB = 0 and 
        (T.SIGN_CUR_WORK = 1 
            or 
            (T.TYPE_TRANSFER_ID = 3 and T.DATE_TRANSFER = 
                (select max(T1.DATE_TRANSFER) from {0}.TRANSFER T1 
				where T1.PER_NUM = NPP.PER_NUM and T1.SIGN_COMB = 0)))
    order by CODE_SUBDIV, PER_NUM
) V