with Tr_per as 
        (select V.TRANSFER_ID, V.PER_NUM, V.DATE_TRANSFER, V.END_TRANSFER, V.SIGN_COMB, V.DEGREE_ID,V.POS_ID,V.SUBDIV_ID,WORKER_ID, FROM_POSITION,
			TYPE_TRANSFER_ID
        from (
            SELECT transfer_id,per_num,WORKER_ID,FROM_POSITION, degree_id,POS_ID,subdiv_id,SIGN_COMB,TYPE_TRANSFER_ID,
				trunc(date_transfer) date_transfer,
                LEAD(trunc(date_transfer),1, DECODE(type_transfer_id,3,TRUNC(date_transfer)+1,date'3000-01-01')) 
                OVER (PARTITION BY WORKER_ID ORDER BY date_transfer)-1/86400 end_transfer 
            FROM {0}.TRANSFER T
            START WITH T.SIGN_CUR_WORK = 1 or T.TYPE_TRANSFER_ID = 3
            CONNECT BY NOCYCLE PRIOR T.FROM_POSITION = T.TRANSFER_ID) V
        WHERE SYSDATE BETWEEN V.DATE_TRANSFER and V.END_TRANSFER)
select EMP_MOBILE_COMM_ID, E.PER_NUM, EM.TRANSFER_ID, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME,
    (SELECT S.CODE_SUBDIV FROM {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    (SELECT S.CODE_SUBDIV FROM {0}.SUBDIV S WHERE S.SUBDIV_ID = TR.SUBDIV_ID) CODE_SUBDIV_CUR,
    (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME,
    (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = TR.POS_ID) POS_NAME_CUR,
	TR.TRANSFER_ID as TRANSFER_ID_CUR, 
	CASE WHEN EM.TRANSFER_ID != TR.TRANSFER_ID THEN 1 ELSE 0 END SING_NEED_CHANGE,
	NVL2(TR.TRANSFER_ID,0,1) SIGN_DISMISS_EMP
from {0}.EMP_MOBILE_COMM EM
JOIN {0}.EMP E on EM.PER_NUM = E.PER_NUM
JOIN {0}.TRANSFER T on T.TRANSFER_ID = EM.TRANSFER_ID
LEFT JOIN TR_PER TR on EM.PER_NUM = TR.PER_NUM
WHERE EM.EMP_MOBILE_COMM_ID = NVL(:p_EMP_MOBILE_COMM_ID, EM.EMP_MOBILE_COMM_ID)