SELECT S.CODE_SUBDIV, CASE WHEN T.SIGN_COMB = 1 THEN 'X' ELSE '' END as SIGN_COMB, 
	CASE WHEN T.TYPE_TRANSFER_ID = 3 THEN '*' ELSE '' END as DISMISS,
	P.POS_NAME, trunc(T.DATE_TRANSFER) as DATE_TRANSFER, T.TR_NUM_ORDER, trunc(T.TR_DATE_ORDER) as TR_DATE_ORDER, R.REASON_NAME
FROM {0}.Transfer T
LEFT JOIN {0}.Subdiv S ON (T.SUBDIV_ID = S.SUBDIV_ID) 
LEFT JOIN {0}.Position P ON (T.POS_ID = P.POS_ID)
LEFT JOIN {0}.Reason_dismiss R ON (T.REASON_ID = R.REASON_ID)  
WHERE T.PER_NUM = {1} and trunc(T.DATE_HIRE) != trunc(to_date('{2}', 'DD.MM.YYYY')) 
ORDER BY T.DATE_TRANSFER