select E.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME, 
    CONTR_EMP, DATE_CONTR, 
    (select S.CODE_SUBDIV from {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    (select S.SUBDIV_NAME from {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) SUBDIV_NAME,    
    (select P.POS_NAME from {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME,
    CASE WHEN AD.CLASSIFIC > 0 THEN AD.CLASSIFIC END CLASSIFIC,
    (select D.CODE_DEGREE from {0}.DEGREE D where D.DEGREE_ID = T.DEGREE_ID) CODE_DEGREE,
    (select D.DEGREE_NAME from {0}.DEGREE D where D.DEGREE_ID = T.DEGREE_ID) DEGREE_NAME
from {0}.TRANSFER T
join {0}.EMP E on T.PER_NUM = E.PER_NUM 
join {0}.ACCOUNT_DATA AD on AD.TRANSFER_ID = DECODE(T.TYPE_TRANSFER_ID,3,T.FROM_POSITION,T.TRANSFER_ID)
where T.TRANSFER_ID = :p_TRANSFER_ID