select (SELECT S.CODE_SUBDIV FROM {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    T.PER_NUM, E.EMP_LAST_NAME||' '||E.EMP_FIRST_NAME||' '||E.EMP_MIDDLE_NAME FIO,
    (SELECT T0.TR_NUM_ORDER FROM {0}.TRANSFER T0 
    WHERE T0.WORKER_ID = T.WORKER_ID and T0.TYPE_TRANSFER_ID = 1) TR_NUM_ORDER,
    (SELECT T0.TR_DATE_ORDER FROM {0}.TRANSFER T0 
    WHERE T0.WORKER_ID = T.WORKER_ID and T0.TYPE_TRANSFER_ID = 1) TR_DATE_ORDER,
    (SELECT T0.DATE_END_CONTR FROM {0}.TRANSFER T0 
    WHERE T0.WORKER_ID = T.WORKER_ID and T0.TYPE_TRANSFER_ID = 1) END_LIMITED_CONTRACT,
    T.DATE_TRANSFER, T.DATE_END_CONTR
from {0}.TRANSFER T 
join {0}.EMP E on T.PER_NUM = E.PER_NUM
WHERE T.TRANSFER_ID = :p_TRANSFER_ID