select (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    T.PER_NUM, T.DATE_HIRE,
    {0}.PADEG.CASE_WORD(e.emp_last_name,'Дательный','last_name',e.emp_sex)||' '||
    {0}.PADEG.CASE_WORD(e.EMP_FIRST_NAME,'Дательный','FIRST_NAME',e.emp_sex)||' '||
    {0}.PADEG.CASE_WORD(e.EMP_MIDDLE_NAME,'Дательный','MIDDLE_NAME',e.emp_sex) FIO,
    DATE_BEGIN_LEAVE PERIOD_BEGIN, --DATE_END_LEAVE PERIOD_END,
    DECODE(CRL.BREAKPOINT_LEAVE,1,CRL.DATE_DEPARTURE,CRL.DATE_END_LEAVE) PERIOD_END,
    R.REL_BIRTH_CERTIFICATE_SER, R.REL_BIRTH_CERTIFICATE_NUM,
    CRL.SIGN_LEAVE_1_5_YEARS, R.REL_BIRTH_DATE,
    (SELECT P.POS_NAME FROM {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME
from {0}.CHILD_CARE_LEAVE CRL
JOIN {0}.RELATIVE R using(RELATIVE_ID)
JOIN {0}.TRANSFER T on (R.PER_NUM=T.PER_NUM)
JOIN {0}.EMP E on R.PER_NUM = E.PER_NUM
where RELATIVE_ID = NVL(:p_RELATIVE_ID,RELATIVE_ID) and T.TRANSFER_ID = :p_TRANSFER_ID and
    :p_DATE BETWEEN CRL.DATE_BEGIN_LEAVE and DECODE(CRL.BREAKPOINT_LEAVE,1,CRL.DATE_DEPARTURE,CRL.DATE_END_LEAVE) 