select T.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME,
    P.SERIA_PASSPORT, P.NUM_PASSPORT, P.WHO_GIVEN, P.WHEN_GIVEN,
    (select S.CODE_SUBDIV from {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    (select S.SUBDIV_NAME from {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) SUBDIV_NAME,
    (select P.POS_NAME from {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME,
	POS_NOTE,
    TARIFF, AD.SALARY, 
    NVL2(AD.TARIFF_GRID_ID, ROUND(AD.SALARY*B.TARIFF,2), ROUND(AD.SALARY*B.TARIFF,0)) SUM_SALARY,
	AD.HARMFUL_ADDITION_ADD, 
	ROUND(NVL2(AD.TARIFF_GRID_ID, ROUND(AD.SALARY*B.TARIFF,2), ROUND(AD.SALARY*B.TARIFF,0))*AD.HARMFUL_ADDITION_ADD/100,2) SUM_HARMFUL_ADDITION, 
	AD.COMB_ADDITION, ROUND(AD.COMB_ADDITION*B.TARIFF,0) SUM_COMB_ADDITION, 
	AD.SECRET_ADDITION, ROUND(AD.SECRET_ADDITION*B.TARIFF,0) SUM_SECRET_ADDITION,
	NVL2(R.REG_CODE_STREET,(select {0}.GET_PART_ADDRESS(R.REG_CODE_STREET,'REGION') from DUAL),
        (SELECT ANK.NAME_REGION FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) REG_REGION,
    NVL2(R.REG_CODE_STREET,(select {0}.GET_PART_ADDRESS(R.REG_CODE_STREET,'DISTRICT') from DUAL),
        (SELECT ANK.NAME_DISTRICT FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) REG_DISTRICT,
    NVL2(R.REG_CODE_STREET,(select {0}.GET_PART_ADDRESS(R.REG_CODE_STREET,'CITY') from DUAL),
        (SELECT ANK.NAME_CITY FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) REG_CITY,
    NVL2(R.REG_CODE_STREET,(select {0}.GET_PART_ADDRESS(R.REG_CODE_STREET,'LOCALITY') from DUAL),
        (SELECT ANK.NAME_LOCALITY FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) REG_LOCALITY,
    NVL2(R.REG_CODE_STREET,(select {0}.GET_PART_ADDRESS(R.REG_CODE_STREET,'STREET') from DUAL),
        (SELECT ANK.NAME_STREET FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) REG_STREET,
    R.REG_HOUSE, R.REG_BULK, R.REG_FLAT,
    B.BDATE DATE_TRANSFER, T.DATE_END_CONTR DATE_TERM_TRANSFER, 
    CASE WHEN NVL(T.CHAR_TRANSFER_ID,T.CHAR_WORK_ID) = 1 THEN 1 END SIGN_CONSTANT_WORK,
    (SELECT CONTR_EMP FROM {0}.TRANSFER T1 
    WHERE T1.WORKER_ID = T.WORKER_ID and T1.TYPE_TRANSFER_ID = 1) TR_NUM_ORDER_HIRE,
    (SELECT DATE_CONTR FROM {0}.TRANSFER T1 
    WHERE T1.WORKER_ID = T.WORKER_ID and T1.TYPE_TRANSFER_ID = 1) TR_DATE_ORDER_HIRE
from {0}.TRANSFER T
join {0}.ACCOUNT_DATA AD on T.TRANSFER_ID = AD.TRANSFER_ID
join {0}.EMP E on T.PER_NUM = E.PER_NUM
join {0}.PASSPORT P on E.PER_NUM = P.PER_NUM
--join {0}.HABIT H on (H.PER_NUM = E.PER_NUM)
join {0}.REGISTR R on (R.PER_NUM = E.PER_NUM)
join (SELECT BT.TARIFF, BT.BDATE, LEAD(BT.BDATE-1/86400,1,DATE '3000-01-01') OVER(ORDER BY BT.BDATE) EDATE 
            FROM {0}.BASE_TARIFF BT) B
        ON SYSDATE between B.BDATE AND B.EDATE
left join {0}.ADDRESS_NONE_KLADR ANK on E.PER_NUM = ANK.PER_NUM
where T.TRANSFER_ID = :p_TRANSFER_ID
ORDER BY EMP_LAST_NAME, EMP_FIRST_NAME, EMP_MIDDLE_NAME