select VIOLATION_EMP_ID, TRANSFER_ID, PER_NUM, DETENTION_DATE, REASON_DETENTION_ID, 
	(SELECT RD.REASON_DETENTION_NAME FROM {0}.REASON_DETENTION RD 
    WHERE RD.REASON_DETENTION_ID = VE.REASON_DETENTION_ID) REASON_DETENTION_NAME,
    /*TYPE_PUNISHMENT_ID, 
    (SELECT TP.TYPE_PUNISHMENT_NAME FROM {0}.TYPE_PUNISHMENT TP
    WHERE TP.TYPE_PUNISHMENT_ID = VE.TYPE_PUNISHMENT_ID) TYPE_PUNISHMENT_NAME,
    TO_CHAR(PERCENT_PUNISHMENT) PERCENT_PUNISHMENT, */
	null TYPE_PUNISHMENT_ID,
    (SELECT distinct LISTAGG(TYPE_PUNISHMENT_NAME||NVL2(PERCENT_PUNISHMENT,' - '||PERCENT_PUNISHMENT||'%',null),';'||chr(13)) 
		WITHIN GROUP(ORDER BY VIOLATION_EMP_ID) OVER()
    FROM {0}.VIOLATION_EMP_PUN LP JOIN {0}.TYPE_PUNISHMENT TP using(TYPE_PUNISHMENT_ID) 
    WHERE LP.VIOLATION_EMP_ID = VE.VIOLATION_EMP_ID) PUNISHMENT,
	PUNISHMENT_NUM_ORDER, PUNISHMENT_DATE_ORDER, COUNT_DAYS, NOTE
from {0}.VIOLATION_EMP VE
WHERE VE.PER_NUM = :p_PER_NUM
union all
select -10 VIOLATION_EMP_ID, VT.TRANSFER_ID, PER_NUM, DETENTION_DATE, null REASON_DETENTION_ID, 
	(SELECT RD.REASON_DETENTION_NAME FROM {0}.REASON_DETENTION RD 
    WHERE RD.REASON_DETENTION_ID = V.REASON_DETENTION_ID) REASON_DETENTION_NAME,
    null TYPE_PUNISHMENT_ID,
    (SELECT distinct LISTAGG(TYPE_PUNISHMENT_NAME||NVL2(PERCENT_PUNISHMENT,' - '||PERCENT_PUNISHMENT||'%',null),';'||chr(13)) 
		WITHIN GROUP(ORDER BY DETENTION_DATE) OVER(PARTITION BY T.PER_NUM)
    FROM {0}.LIST_OF_PUNISHMENT LP JOIN {0}.TYPE_PUNISHMENT TP using(TYPE_PUNISHMENT_ID) 
    WHERE LP.PUNISHMENT_ID = PU.PUNISHMENT_ID and SIGN_PUNISHMENT_CHIEF = 0) PUNISHMENT,
    PU.PUNISHMENT_NUM_ORDER, PU.PUNISHMENT_DATE_ORDER, null COUNT_DAYS, null NOTE
from {0}.VIOLATION V
join {0}.VIOLATOR VT on V.VIOLATION_ID = VT.VIOLATION_ID
join {0}.TRANSFER T on VT.TRANSFER_ID = T.TRANSFER_ID
left join {0}.PUNISHMENT PU on V.VIOLATION_ID = PU.VIOLATION_ID
WHERE T.PER_NUM = :p_PER_NUM
ORDER BY DETENTION_DATE