select TARIFF_GRID_ID, CODE_TARIFF_GRID, TAR_CLASSIF, TAR_SAL, TAR_HOUR, TAR_MONTH, 
	TAR_DATE, TARIFF_END_DATE, TARIFF, CAR_ID 
from {0}.TARIFF_GRID_SALARY TG
/*WHERE TG.TAR_DATE = 
    (select B1.BDATE from 
        (select B.BASE_TARIFF_ID, B.BDATE, LEAD(B.BDATE-1/86400,1,DATE '3000-01-01') OVER(ORDER BY B.BDATE) EDATE, B.TARIFF
        FROM {0}.BASE_TARIFF B ) B1 
    WHERE :p_date_transfer between B1.BDATE and B1.EDATE)*/