select 
    E.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME, E.EMP_BIRTH_DATE, E.EMP_SEX, E.PERCO_SYNC_ID,
	T.TRANSFER_ID, NVL2(T.TRANSFER_ID, 0, 1) FL_LACK_TRANS
from {0}.EMP E
left join 
    (select distinct FIRST_VALUE(T.TRANSFER_ID) OVER(PARTITION BY T.PER_NUM ORDER BY T.DATE_TRANSFER DESC) TRANSFER_ID,
        T.PER_NUM
    FROM {0}.TRANSFER T where T.TYPE_TRANSFER_ID = 7) T on (E.PER_NUM = T.PER_NUM)
left JOIN {0}.TRANSFER T1 on (T.TRANSFER_ID = T1.TRANSFER_ID)
WHERE (T.TRANSFER_ID is not null or (T.TRANSFER_ID is null and E.PER_NUM > '79000')) 
	and
    NVL(:p_EMP_LAST_NAME,E.EMP_LAST_NAME)=E.EMP_LAST_NAME and 
    NVL(:p_EMP_FIRST_NAME,E.EMP_FIRST_NAME)=E.EMP_FIRST_NAME and 
    NVL(:p_EMP_MIDDLE_NAME,E.EMP_MIDDLE_NAME)=E.EMP_MIDDLE_NAME and 
    NVL(:p_PER_NUM,E.PER_NUM)=E.PER_NUM and 
    (:p_SIGN_STUDENT is null or :p_SIGN_STUDENT = DECODE(T1.DEGREE_ID,11,1,0)) and
    NVL(T1.DATE_TRANSFER,DATE '3001-01-01') <= NVL(:p_end_period,DATE '3001-01-01') and 
    NVL(T1.DATE_END_CONTR,DATE '3001-01-01') >= NVL(:p_begin_period,DATE '1001-01-01')
ORDER BY E.PER_NUM
