with SUBD as 
    (select SUBDIV_ID FROM {0}.SUBDIV
        start with subdiv_id in (
            select subdiv_id from {0}.access_subdiv 
            where upper(user_name) = ora_login_user and upper(app_name) = 'KADR')
        connect by prior subdiv_id = parent_id)
select T.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME,
    P.SERIA_PASSPORT, P.NUM_PASSPORT, P.WHO_GIVEN, P.WHEN_GIVEN,
    (select S.CODE_SUBDIV from {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    (select S.SUBDIV_NAME from {0}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) SUBDIV_NAME,
    (select P.POS_NAME from {0}.POSITION P WHERE P.POS_ID = T.POS_ID) POS_NAME,
	POS_NOTE,
    TARIFF, AD.SALARY, 
    NVL2(AD.TARIFF_GRID_ID, ROUND(AD.SALARY*B.TARIFF,2), ROUND(AD.SALARY*B.TARIFF,0)) SUM_SALARY,
	AD.HARMFUL_ADDITION_ADD, 
	ROUND(NVL2(AD.TARIFF_GRID_ID, ROUND(AD.SALARY*B.TARIFF,2), ROUND(AD.SALARY*B.TARIFF,0))*AD.HARMFUL_ADDITION_ADD/100,2) SUM_HARMFUL_ADDITION, 
	AD.COMB_ADDITION, ROUND(AD.COMB_ADDITION*B.TARIFF,0) SUM_COMB_ADDITION, 
	AD.SECRET_ADDITION, ROUND(AD.SECRET_ADDITION*B.TARIFF,0) SUM_SECRET_ADDITION,
	NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'REGION') from DUAL),
        (SELECT ANK.NAME_REGION FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_REGION,
    NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'DISTRICT') from DUAL),
        (SELECT ANK.NAME_DISTRICT FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_DISTRICT,
    NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'CITY') from DUAL),
        (SELECT ANK.NAME_CITY FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_CITY,
    NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'LOCALITY') from DUAL),
        (SELECT ANK.NAME_LOCALITY FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_LOCALITY,
    NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'STREET') from DUAL),
        (SELECT ANK.NAME_STREET FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_STREET,
    H.HAB_HOUSE, H.HAB_BULK, H.HAB_FLAT,
    B.BDATE DATE_TRANSFER, T.DATE_END_CONTR DATE_TERM_TRANSFER, 
    CASE WHEN NVL(T.CHAR_TRANSFER_ID,T.CHAR_WORK_ID) = 1 THEN 1 END SIGN_CONSTANT_WORK
from {0}.TRANSFER T
join {0}.ACCOUNT_DATA AD on T.TRANSFER_ID = AD.TRANSFER_ID
join {0}.EMP E on T.PER_NUM = E.PER_NUM
join {0}.PASSPORT P on E.PER_NUM = P.PER_NUM
join {0}.HABIT H on (H.PER_NUM = E.PER_NUM)
join (SELECT BT.TARIFF, BT.BDATE, LEAD(BT.BDATE-1/86400,1,DATE '3000-01-01') OVER(ORDER BY BT.BDATE) EDATE 
            FROM {0}.BASE_TARIFF BT) B
        ON :p_DATE_TARIFF between B.BDATE AND B.EDATE
left join {0}.ADDRESS_NONE_KLADR ANK on E.PER_NUM = ANK.PER_NUM
where T.SIGN_CUR_WORK = 1 and T.DATE_TRANSFER < DATE '2016-01-01' and 
    T.SUBDIV_ID in (SELECT SUBDIV_ID FROM SUBD) and 
    T.SUBDIV_ID = NVL(:p_SUBDIV_ID,T.SUBDIV_ID)
ORDER BY EMP_LAST_NAME, EMP_FIRST_NAME, EMP_MIDDLE_NAME