with APPR as (
    select DATE_APPROVAL, USER_NAME,
        (SELECT EMP_LAST_NAME||' '||SUBSTR(EMP_FIRST_NAME,1,1)||'.'||SUBSTR(EMP_MIDDLE_NAME,1,1)||'.'
        FROM {0}.EMP E WHERE E.PER_NUM = {0}.GET_PER_NUM_FROM_USER_NAME(USER_NAME)) USER_FIO,
        ROLE_NAME,
        DECODE(ROLE_NAME, 
            'STAFF_CHIEF_HR_DEPT','Отдел кадров',
            'STAFF_LEGAL_DEPT','Юридическое управление',
            'STAFF_CHIEF_ECON_DEPT','Отдел ОТиЗП',
            'STAFF_CHIEF_SUBDIV','Руководитель подразделения',
            'STAFF_CHIEF_BUREAU_TARIFF','БТиЗ подразделения (экономист)') NOTE_ROLE_NAME,
        DECODE(ROLE_NAME, 'STAFF_CHIEF_HR_DEPT',1,'STAFF_LEGAL_DEPT',2,'STAFF_CHIEF_ECON_DEPT',3,
            'STAFF_CHIEF_SUBDIV',4,'STAFF_CHIEF_BUREAU_TARIFF',5) NUMBER_ROLE 
    from (
        select DISTINCT FIRST_VALUE(PA.DATE_APPROVAL) 
                              OVER(PARTITION BY PPA.ROLE_NAME ORDER BY PA.DATE_APPROVAL DESC) DATE_APPROVAL, 
            FIRST_VALUE(PA.USER_NAME) OVER(PARTITION BY PPA.ROLE_NAME ORDER BY PA.DATE_APPROVAL DESC) USER_NAME, 
            FIRST_VALUE(PPA.ROLE_NAME) OVER(PARTITION BY PPA.ROLE_NAME ORDER BY PA.DATE_APPROVAL DESC) ROLE_NAME 
        from {0}.PROJECT_APPROVAL PA 
        join {0}.PROJECT_PLAN_APPROVAL PPA using(PROJECT_PLAN_APPROVAL_ID)
        where PA.PROJECT_TRANSFER_ID = :p_PROJECT_TRANSFER_ID)
    )
select NOTE_ROLE_NAME, 'ЭЦП' NOTE, DATE_APPROVAL, USER_FIO, ROLE_NAME
from APPR where NUMBER_ROLE is not null
ORDER BY NUMBER_ROLE