with APPR as (
    select DATE_APPROVAL, USER_NAME,
        (SELECT EMP_LAST_NAME||' '||SUBSTR(EMP_FIRST_NAME,1,1)||'.'||SUBSTR(EMP_MIDDLE_NAME,1,1)||'.'
        FROM {0}.EMP E WHERE E.PER_NUM = {0}.GET_PER_NUM_FROM_USER_NAME(USER_NAME)) USER_FIO,
        ROLE_NAME, PROJECT_PLAN_APPROVAL_ID,
        DECODE(ROLE_NAME, 
            'STAFF_CHIEF_HR_DEPT','Отдел кадров',
            'STAFF_CHIEF_ECON_DEPT','Отдел ОТиЗП',
            'STAFF_CHIEF_SUBDIV','Руководитель подразделения',
            'STAFF_TRAINING_PERS','Отдел 35') NOTE_ROLE_NAME
    from (
        select DISTINCT FIRST_VALUE(PA.DATE_APPROVAL) 
                              OVER(PARTITION BY PPA.ROLE_NAME, PROJECT_PLAN_APPROVAL_ID ORDER BY PA.DATE_APPROVAL DESC) DATE_APPROVAL, 
            FIRST_VALUE(PA.USER_NAME) OVER(PARTITION BY PPA.ROLE_NAME, PROJECT_PLAN_APPROVAL_ID ORDER BY PA.DATE_APPROVAL DESC) USER_NAME, 
            FIRST_VALUE(PPA.ROLE_NAME) OVER(PARTITION BY PPA.ROLE_NAME, PROJECT_PLAN_APPROVAL_ID ORDER BY PA.DATE_APPROVAL DESC) ROLE_NAME,
            PROJECT_PLAN_APPROVAL_ID 
        from {0}.PROJECT_STATEMENT_APPROVAL PA 
        join {0}.PROJECT_PLAN_APPROVAL PPA using(PROJECT_PLAN_APPROVAL_ID)
        where PA.PROJECT_STATEMENT_ID = :p_PROJECT_STATEMENT_ID
        )
    )
select NOTE_ROLE_NAME, 'ЭЦП' NOTE, DATE_APPROVAL, USER_FIO, ROLE_NAME
from APPR 
where ROLE_NAME != 'STAFF_PERSONNEL'
ORDER BY PROJECT_PLAN_APPROVAL_ID DESC