with ED AS (
        select ROWNUM RN, PER_NUM, TE_NAME, TS_NAME, INSTIT_NAME, NAME_SPEC, QUAL_NAME, YEAR_GRADUATING
        from (
            select E.PER_NUM, TE.TE_NAME, TS.TS_NAME, I.INSTIT_NAME, SP.NAME_SPEC, 
				(SELECT Q.QUAL_NAME FROM {0}.QUAL Q WHERE Q.QUAL_ID = E.QUAL_ID) QUAL_NAME, 
                EXTRACT(YEAR FROM E.YEAR_GRADUATING) YEAR_GRADUATING
            from {0}.EDU E
            LEFT join {0}.TYPE_EDU TE using(TYPE_EDU_ID)
            LEFT JOIN {0}.TYPE_STUDY TS using(TYPE_STUDY_ID)
            LEFT JOIN {0}.INSTIT I using(INSTIT_ID)
            LEFT JOIN {0}.SPECIALITY SP using(SPEC_ID)
            where PER_NUM = :p_PER_NUM
            ORDER BY TE_PRIORITY, YEAR_GRADUATING
        )
    ),
    TERM as ( 
    select TYPE_TERM, SIGN_BASE_TEMP_TRANSFER, SIGN_REPL_EMP, BASE_TERM_TRANSFER_NAME, DATE_TERM_TRANSFER,
        (select LISTAGG((select E.EMP_LAST_NAME||' '||Substr(E.EMP_FIRST_NAME,1,1)||'.'||Substr(E.EMP_MIDDLE_NAME,1,1) 
                        from {0}.EMP E join {0}.TRANSFER T using(PER_NUM) 
                        where T.TRANSFER_ID = LRE.TRANSFER_ID), ',') 
            WITHIN GROUP(ORDER BY LRE.ORDER_REPL_EMP) 
        FROM {0}.PROJECT_LIST_REPL_EMP LRE     
        WHERE LRE.PROJECT_TERM_TRANSFER_ID = PTT.PROJECT_TERM_TRANSFER_ID) LIST_REPL_EMP
    from {0}.PROJECT_TERM_TRANSFER PTT 
    LEFT JOIN {0}.TYPE_TERM_TRANSFER TTT using(TYPE_TERM_TRANSFER_ID)
    LEFT JOIN {0}.BASE_TERM_TRANSFER BTT using(BASE_TERM_TRANSFER_ID)
    WHERE PTT.PROJECT_TRANSFER_ID = :p_PROJECT_TRANSFER_ID
    )
select E.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME, E.EMP_BIRTH_DATE,
    PT.TR_NUM_ORDER, PT.TR_DATE_ORDER, PT.DATE_HIRE, PT.SIGN_COMB, PT.DATE_TRANSFER,
    (select S.CODE_SUBDIV from {0}.SUBDIV S where S.SUBDIV_ID = PT.SUBDIV_ID) CODE_SUBDIV,
    (select S.SUBDIV_NAME from {0}.SUBDIV S where S.SUBDIV_ID = PT.SUBDIV_ID) SUBDIV_NAME,
    (select P.POS_NAME from {0}.POSITION P where P.POS_ID = PT.POS_ID) POS_NAME,
    (select P.CODE_POS from {0}.POSITION P where P.POS_ID = PT.POS_ID) CODE_POS,
	POS_NOTE,
    PT.CLASSIFIC, PT.SALARY,
    NVL2(PT.TARIFF_GRID_ID, 
		--ROUND(PT.SALARY*B.TARIFF,2),
        (SELECT TS.TAR_MONTH FROM {0}.TARIFF_GRID_SALARY TS 
        WHERE TS.TARIFF_GRID_ID = PT.TARIFF_GRID_ID and TS.TAR_CLASSIF = PT.CLASSIFIC and        
            PT.DATE_TRANSFER between TS.TAR_DATE and TS.TARIFF_END_DATE and 
            TS.TAR_SAL = PT.SALARY),
		ROUND(PT.SALARY*B.TARIFF,0)) SUM_SALARY,
    (select TG.CODE_TARIFF_GRID from {0}.TARIFF_GRID TG where TG.TARIFF_GRID_ID = PT.TARIFF_GRID_ID) CODE_TARIFF_GRID,
    COMB_ADDITION, ROUND(PT.COMB_ADDITION*B.TARIFF,0) SUM_COMB_ADDITION, HARMFUL_ADDITION_ADD,
    (select FP.NAME_FORM_PAY from {0}.FORM_PAY FP where FP.FORM_PAY = PT.FORM_PAY) NAME_FORM_PAY,
    (select D.CODE_DEGREE from {0}.DEGREE D where D.DEGREE_ID = PT.DEGREE_ID) CODE_DEGREE,
    (select D.DEGREE_NAME from {0}.DEGREE D where D.DEGREE_ID = PT.DEGREE_ID) DEGREE_NAME, 
    PT.SIGN_ADD, PT.DATE_ADD, PT.PROBA_PERIOD, PT.CONTR_EMP, PT.DATE_CONTR, PT.DATE_END_CONTR,
    SERIA_PASSPORT, NUM_PASSPORT, WHEN_GIVEN, WHO_GIVEN,    
    (select FO.CODE_FORM_OPERATION from {0}.FORM_OPERATION FO 
    where FO.FORM_OPERATION_ID = PT.FORM_OPERATION_ID) CODE_FORM_OPERATION,
    V_ED.TE_NAME, V_ED.TS_NAME, V_ED.INSTIT_NAME, V_ED.NAME_SPEC, V_ED.QUAL_NAME, V_ED.YEAR_GRADUATING,
    NVL2(V_ED2.PER_NUM, V_ED2.TE_NAME||', '||V_ED2.TS_NAME||', '||V_ED2.INSTIT_NAME||', '||V_ED2.NAME_SPEC||', '||
        V_ED2.QUAL_NAME||', '||V_ED2.YEAR_GRADUATING, '') NOTE_EDU2,
    0 as SIGN_DIR_SIGNATURE, '' FIO_SIGNATURE, FORM_PAY, NVL(PT.SIGN_MAT_RESP_CONTR,0) SIGN_MAT_RESP_CONTR,
    (select PP.SPECIAL_CONDITIONS||' '||PP.KPS from {0}.PRIVILEGED_POSITION PP 
    where PP.PRIVILEGED_POSITION_ID = PAC.PRIVILEGED_POSITION_ID) PRIVILEGED_POSITION,
    CASE WHEN PT.HARMFUL_VAC>0 THEN HARMFUL_VAC END HARMFUL_VAC,
    CASE WHEN PT.ADDITIONAL_VAC>0 THEN ADDITIONAL_VAC END ADDITIONAL_VAC,
    (SELECT BASE_TERM_TRANSFER_NAME FROM TERM WHERE TYPE_TERM = DECODE(PT.TYPE_TRANSFER_ID,1,1,2)) BASE_TERM_TRANSFER_NAME,
    (SELECT DATE_TERM_TRANSFER FROM TERM WHERE TYPE_TERM = DECODE(PT.TYPE_TRANSFER_ID,1,1,2)) DATE_TERM_TRANSFER,
    (SELECT LIST_REPL_EMP FROM TERM WHERE TYPE_TERM = DECODE(PT.TYPE_TRANSFER_ID,1,1,2)) LIST_REPL_EMP,
    (SELECT WT.NUMBER_FOR_ORDER FROM {0}.WORKING_TIME WT 
    WHERE WT.WORKING_TIME_ID = PT.WORKING_TIME_ID) WORKING_TIME_NUMBER, 
	case when upper(WORKING_TIME_COMMENT) like '%Œ—ÕŒ¬¿Õ»≈%' then substr(WORKING_TIME_COMMENT, 1, instr(UPPER(WORKING_TIME_COMMENT), 'Œ—ÕŒ¬¿Õ»≈')-1) else WORKING_TIME_COMMENT end WORKING_TIME_COMMENT,
	case when upper(WORKING_TIME_COMMENT) like '%Œ—ÕŒ¬¿Õ»≈%' then substr(WORKING_TIME_COMMENT, instr(UPPER(WORKING_TIME_COMMENT), 'Œ—ÕŒ¬¿Õ»≈')+10) else null end WORKING_TIME_REASON,
	NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'REGION') from DUAL),
        (SELECT ANK.NAME_REGION FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_REGION,
    NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'DISTRICT') from DUAL),
        (SELECT ANK.NAME_DISTRICT FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_DISTRICT,
    NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'CITY') from DUAL),
        (SELECT ANK.NAME_CITY FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_CITY,
    NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'LOCALITY') from DUAL),
        (SELECT ANK.NAME_LOCALITY FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_LOCALITY,
    NVL2(H.HAB_CODE_STREET,(select {0}.GET_PART_ADDRESS(H.HAB_CODE_STREET,'STREET') from DUAL),
        (SELECT ANK.NAME_STREET FROM {0}.ADDRESS_NONE_KLADR ANK WHERE ANK.PER_NUM = E.PER_NUM)) HAB_STREET,
    H.HAB_HOUSE, H.HAB_BULK, H.HAB_FLAT, 
	OTHER_LIABILITY_BOSS,
    (SELECT CONTR_EMP FROM {0}.TRANSFER T 
    WHERE T.WORKER_ID = PT.WORKER_ID and T.TYPE_TRANSFER_ID = 1) TR_NUM_ORDER_HIRE,
    (SELECT DATE_CONTR FROM {0}.TRANSFER T 
    WHERE T.WORKER_ID = PT.WORKER_ID and T.TYPE_TRANSFER_ID = 1) TR_DATE_ORDER_HIRE
from {0}.PROJECT_TRANSFER PT
join {0}.EMP E on PT.PER_NUM = E.PER_NUM
join {0}.PASSPORT PAS on (E.PER_NUM = PAS.PER_NUM)
join {0}.HABIT H on (H.PER_NUM = E.PER_NUM)
join (SELECT BT.TARIFF, BT.BDATE, LEAD(BT.BDATE-1/86400,1,DATE '3000-01-01') OVER(ORDER BY BT.BDATE) EDATE 
            FROM {0}.BASE_TARIFF BT) B
        ON PT.DATE_TRANSFER between B.BDATE AND B.EDATE
left join (select * from ED WHERE RN = 1) V_ED on (E.PER_NUM = V_ED.PER_NUM)
left join (select * from ED WHERE RN = 2) V_ED2 on (E.PER_NUM = V_ED2.PER_NUM)
left join {0}.PROJECT_ADD_CONDITION PAC on (PT.PROJECT_TRANSFER_ID = PAC.PROJECT_TRANSFER_ID)
where PT.PROJECT_TRANSFER_ID = :p_PROJECT_TRANSFER_ID