select TC.TYPE_CONDITION_ID, TYPE_CONDITION_NAME, PROJECT_WORK_CONDITIONS_ID, PROJECT_TRANSFER_ID, 
    PWC.TYPE_CONDITION_ID TYPE_CONDITION_ID_REF, CONDITIONS_OF_WORK_ID, SIGN_MAIN_TYPE
from {0}.TYPE_CONDITION TC
left join 
    (select * from {0}.PROJECT_WORK_CONDITIONS PWC
    where PWC.PROJECT_TRANSFER_ID = :p_PROJECT_TRANSFER_ID) PWC on TC.TYPE_CONDITION_ID = PWC.TYPE_CONDITION_ID
ORDER BY ORDER_FOR_EDIT--SIGN_MAIN_TYPE desc, TYPE_CONDITION_NAME