select PROJECT_LIST_REPL_EMP_ID, PROJECT_TERM_TRANSFER_ID, LRE.TRANSFER_ID, ORDER_REPL_EMP,
    E.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME 
from {0}.PROJECT_LIST_REPL_EMP LRE
join {0}.TRANSFER T on LRE.TRANSFER_ID = T.TRANSFER_ID
JOIN {0}.EMP E on T.PER_NUM = E.PER_NUM
WHERE PROJECT_TERM_TRANSFER_ID=:p_PROJECT_TERM_TRANSFER_ID
ORDER BY ORDER_REPL_EMP,PROJECT_LIST_REPL_EMP_ID

