select PROJECT_TERM_TRANSFER_ID, PROJECT_TRANSFER_ID, TYPE_TERM_TRANSFER_ID, DATE_TERM_TRANSFER, BASE_TERM_TRANSFER_ID, TYPE_TERM 
from {0}.PROJECT_TERM_TRANSFER TT
where TT.PROJECT_TRANSFER_ID = :p_PROJECT_TRANSFER_ID and TT.TYPE_TERM = :p_TYPE_TERM