select TERM_TRANSFER_ID, TRANSFER_PROJECT_ID, TYPE_TERM_TRANSFER_ID, DATE_TERM_TRANSFER, BASE_TERM_TRANSFER_ID, TYPE_TERM 
from {0}.TERM_TRANSFER TT
where TT.TRANSFER_PROJECT_ID = :p_TRANSFER_PROJECT_ID and TT.TYPE_TERM = :p_TYPE_TERM