//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3053
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Elegant.Ui.CommandSourceAttribute("Kadr.ApplicationCommands", "Kadr.ApplicationCommands")]

namespace Kadr
{
    //  This class is required for commands suppport.
// Do not modify this code inside the editor.

public class ApplicationCommands
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command UserName = new Elegant.Ui.Command("UserName");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command User = new Elegant.Ui.Command("User");
}
}
