SELECT PREV_WORK_ID, PER_NUM, PW_FIRM, PW_NAME_POS, PW_DATE_START, PW_DATE_END, 
	0 as STAGYEAR, 0 as STAGMONTH, 0 as STAGDAY, WORK_IN_FACT, MEDICAL_SIGN
FROM {0}.PREV_WORK PW
WHERE PW.PER_NUM = :p_PER_NUM